// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/noahyang/deviceIdentify.jce'
// **********************************************************************

package com.qq.jce.DEVICE_IDENTIFY_SVR;

public final class DeviceIconPath extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "DEVICE_IDENTIFY_SVR.DeviceIconPath";
    }

    public String fullClassName()
    {
        return "com.qq.jce.DEVICE_IDENTIFY_SVR.DeviceIconPath";
    }

    public com.qq.jce.DEVICE_IDENTIFY_SVR.IconDetails stLargeIcon = null;

    public com.qq.jce.DEVICE_IDENTIFY_SVR.IconDetails stLargeIconQQ = null;

    public com.qq.jce.DEVICE_IDENTIFY_SVR.IconDetails stThumbIconQQ = null;

    public com.qq.jce.DEVICE_IDENTIFY_SVR.IconDetails stLargeIconQQV2 = null;

    public com.qq.jce.DEVICE_IDENTIFY_SVR.IconDetails getStLargeIcon()
    {
        return stLargeIcon;
    }

    public void  setStLargeIcon(com.qq.jce.DEVICE_IDENTIFY_SVR.IconDetails stLargeIcon)
    {
        this.stLargeIcon = stLargeIcon;
    }

    public com.qq.jce.DEVICE_IDENTIFY_SVR.IconDetails getStLargeIconQQ()
    {
        return stLargeIconQQ;
    }

    public void  setStLargeIconQQ(com.qq.jce.DEVICE_IDENTIFY_SVR.IconDetails stLargeIconQQ)
    {
        this.stLargeIconQQ = stLargeIconQQ;
    }

    public com.qq.jce.DEVICE_IDENTIFY_SVR.IconDetails getStThumbIconQQ()
    {
        return stThumbIconQQ;
    }

    public void  setStThumbIconQQ(com.qq.jce.DEVICE_IDENTIFY_SVR.IconDetails stThumbIconQQ)
    {
        this.stThumbIconQQ = stThumbIconQQ;
    }

    public com.qq.jce.DEVICE_IDENTIFY_SVR.IconDetails getStLargeIconQQV2()
    {
        return stLargeIconQQV2;
    }

    public void  setStLargeIconQQV2(com.qq.jce.DEVICE_IDENTIFY_SVR.IconDetails stLargeIconQQV2)
    {
        this.stLargeIconQQV2 = stLargeIconQQV2;
    }

    public DeviceIconPath()
    {
    }

    public DeviceIconPath(com.qq.jce.DEVICE_IDENTIFY_SVR.IconDetails stLargeIcon, com.qq.jce.DEVICE_IDENTIFY_SVR.IconDetails stLargeIconQQ, com.qq.jce.DEVICE_IDENTIFY_SVR.IconDetails stThumbIconQQ, com.qq.jce.DEVICE_IDENTIFY_SVR.IconDetails stLargeIconQQV2)
    {
        this.stLargeIcon = stLargeIcon;
        this.stLargeIconQQ = stLargeIconQQ;
        this.stThumbIconQQ = stThumbIconQQ;
        this.stLargeIconQQV2 = stLargeIconQQV2;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        DeviceIconPath t = (DeviceIconPath) o;
        return (
            com.qq.taf.jce.JceUtil.equals(stLargeIcon, t.stLargeIcon) && 
            com.qq.taf.jce.JceUtil.equals(stLargeIconQQ, t.stLargeIconQQ) && 
            com.qq.taf.jce.JceUtil.equals(stThumbIconQQ, t.stThumbIconQQ) && 
            com.qq.taf.jce.JceUtil.equals(stLargeIconQQV2, t.stLargeIconQQV2) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(stLargeIcon, 0);
        _os.write(stLargeIconQQ, 1);
        _os.write(stThumbIconQQ, 2);
        _os.write(stLargeIconQQV2, 3);
    }

    static com.qq.jce.DEVICE_IDENTIFY_SVR.IconDetails cache_stLargeIcon;
    static com.qq.jce.DEVICE_IDENTIFY_SVR.IconDetails cache_stLargeIconQQ;
    static com.qq.jce.DEVICE_IDENTIFY_SVR.IconDetails cache_stThumbIconQQ;
    static com.qq.jce.DEVICE_IDENTIFY_SVR.IconDetails cache_stLargeIconQQV2;

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        if(null == cache_stLargeIcon)
        {
            cache_stLargeIcon = new com.qq.jce.DEVICE_IDENTIFY_SVR.IconDetails();
        }
        this.stLargeIcon = (com.qq.jce.DEVICE_IDENTIFY_SVR.IconDetails) _is.read(cache_stLargeIcon, 0, true);
        if(null == cache_stLargeIconQQ)
        {
            cache_stLargeIconQQ = new com.qq.jce.DEVICE_IDENTIFY_SVR.IconDetails();
        }
        this.stLargeIconQQ = (com.qq.jce.DEVICE_IDENTIFY_SVR.IconDetails) _is.read(cache_stLargeIconQQ, 1, true);
        if(null == cache_stThumbIconQQ)
        {
            cache_stThumbIconQQ = new com.qq.jce.DEVICE_IDENTIFY_SVR.IconDetails();
        }
        this.stThumbIconQQ = (com.qq.jce.DEVICE_IDENTIFY_SVR.IconDetails) _is.read(cache_stThumbIconQQ, 2, true);
        if(null == cache_stLargeIconQQV2)
        {
            cache_stLargeIconQQV2 = new com.qq.jce.DEVICE_IDENTIFY_SVR.IconDetails();
        }
        this.stLargeIconQQV2 = (com.qq.jce.DEVICE_IDENTIFY_SVR.IconDetails) _is.read(cache_stLargeIconQQV2, 3, true);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(stLargeIcon, "stLargeIcon");
        _ds.display(stLargeIconQQ, "stLargeIconQQ");
        _ds.display(stThumbIconQQ, "stThumbIconQQ");
        _ds.display(stLargeIconQQV2, "stLargeIconQQV2");
    }

    public void displaySimple(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.displaySimple(stLargeIcon, true);
        _ds.displaySimple(stLargeIconQQ, true);
        _ds.displaySimple(stThumbIconQQ, true);
        _ds.displaySimple(stLargeIconQQV2, false);
    }

}

