// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/noahyang/deviceIdentify.jce'
// **********************************************************************

package com.qq.jce.DEVICE_IDENTIFY_SVR;

public final class DeviceDetailsResponse extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "DEVICE_IDENTIFY_SVR.DeviceDetailsResponse";
    }

    public String fullClassName()
    {
        return "com.qq.jce.DEVICE_IDENTIFY_SVR.DeviceDetailsResponse";
    }

    public int eResult = 0;

    public com.qq.jce.DEVICE_IDENTIFY_SVR.DeviceDetails stDetails = null;

    public int getEResult()
    {
        return eResult;
    }

    public void  setEResult(int eResult)
    {
        this.eResult = eResult;
    }

    public com.qq.jce.DEVICE_IDENTIFY_SVR.DeviceDetails getStDetails()
    {
        return stDetails;
    }

    public void  setStDetails(com.qq.jce.DEVICE_IDENTIFY_SVR.DeviceDetails stDetails)
    {
        this.stDetails = stDetails;
    }

    public DeviceDetailsResponse()
    {
    }

    public DeviceDetailsResponse(int eResult, com.qq.jce.DEVICE_IDENTIFY_SVR.DeviceDetails stDetails)
    {
        this.eResult = eResult;
        this.stDetails = stDetails;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        DeviceDetailsResponse t = (DeviceDetailsResponse) o;
        return (
            com.qq.taf.jce.JceUtil.equals(eResult, t.eResult) && 
            com.qq.taf.jce.JceUtil.equals(stDetails, t.stDetails) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(eResult, 0);
        _os.write(stDetails, 1);
    }

    static int cache_eResult;
    static com.qq.jce.DEVICE_IDENTIFY_SVR.DeviceDetails cache_stDetails;

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.eResult = (int) _is.read(eResult, 0, true);
        if(null == cache_stDetails)
        {
            cache_stDetails = new com.qq.jce.DEVICE_IDENTIFY_SVR.DeviceDetails();
        }
        this.stDetails = (com.qq.jce.DEVICE_IDENTIFY_SVR.DeviceDetails) _is.read(cache_stDetails, 1, true);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(eResult, "eResult");
        _ds.display(stDetails, "stDetails");
    }

    public void displaySimple(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.displaySimple(eResult, true);
        _ds.displaySimple(stDetails, false);
    }

}

