// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/noahyang/deviceIdentify.jce'
// **********************************************************************

package com.qq.jce.DEVICE_IDENTIFY_SVR;

public final class DeviceScreen extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "DEVICE_IDENTIFY_SVR.DeviceScreen";
    }

    public String fullClassName()
    {
        return "com.qq.jce.DEVICE_IDENTIFY_SVR.DeviceScreen";
    }

    public int nType = 0;

    public String sResolution = "";

    public String sStartPoint = "";

    public String sScreenSize = "";

    public String sIconSize = "";

    public int nRotate = 0;

    public int getNType()
    {
        return nType;
    }

    public void  setNType(int nType)
    {
        this.nType = nType;
    }

    public String getSResolution()
    {
        return sResolution;
    }

    public void  setSResolution(String sResolution)
    {
        this.sResolution = sResolution;
    }

    public String getSStartPoint()
    {
        return sStartPoint;
    }

    public void  setSStartPoint(String sStartPoint)
    {
        this.sStartPoint = sStartPoint;
    }

    public String getSScreenSize()
    {
        return sScreenSize;
    }

    public void  setSScreenSize(String sScreenSize)
    {
        this.sScreenSize = sScreenSize;
    }

    public String getSIconSize()
    {
        return sIconSize;
    }

    public void  setSIconSize(String sIconSize)
    {
        this.sIconSize = sIconSize;
    }

    public int getNRotate()
    {
        return nRotate;
    }

    public void  setNRotate(int nRotate)
    {
        this.nRotate = nRotate;
    }

    public DeviceScreen()
    {
    }

    public DeviceScreen(int nType, String sResolution, String sStartPoint, String sScreenSize, String sIconSize, int nRotate)
    {
        this.nType = nType;
        this.sResolution = sResolution;
        this.sStartPoint = sStartPoint;
        this.sScreenSize = sScreenSize;
        this.sIconSize = sIconSize;
        this.nRotate = nRotate;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        DeviceScreen t = (DeviceScreen) o;
        return (
            com.qq.taf.jce.JceUtil.equals(nType, t.nType) && 
            com.qq.taf.jce.JceUtil.equals(sResolution, t.sResolution) && 
            com.qq.taf.jce.JceUtil.equals(sStartPoint, t.sStartPoint) && 
            com.qq.taf.jce.JceUtil.equals(sScreenSize, t.sScreenSize) && 
            com.qq.taf.jce.JceUtil.equals(sIconSize, t.sIconSize) && 
            com.qq.taf.jce.JceUtil.equals(nRotate, t.nRotate) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(nType, 0);
        _os.write(sResolution, 1);
        _os.write(sStartPoint, 2);
        _os.write(sScreenSize, 3);
        _os.write(sIconSize, 4);
        _os.write(nRotate, 5);
    }


    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.nType = (int) _is.read(nType, 0, true);
        this.sResolution =  _is.readString(1, true);
        this.sStartPoint =  _is.readString(2, true);
        this.sScreenSize =  _is.readString(3, true);
        this.sIconSize =  _is.readString(4, true);
        this.nRotate = (int) _is.read(nRotate, 5, true);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(nType, "nType");
        _ds.display(sResolution, "sResolution");
        _ds.display(sStartPoint, "sStartPoint");
        _ds.display(sScreenSize, "sScreenSize");
        _ds.display(sIconSize, "sIconSize");
        _ds.display(nRotate, "nRotate");
    }

    public void displaySimple(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.displaySimple(nType, true);
        _ds.displaySimple(sResolution, true);
        _ds.displaySimple(sStartPoint, true);
        _ds.displaySimple(sScreenSize, true);
        _ds.displaySimple(sIconSize, true);
        _ds.displaySimple(nRotate, false);
    }

}

