// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/noahyang/deviceIdentify.jce'
// **********************************************************************

package com.qq.jce.DEVICE_IDENTIFY_SVR;

public final class DeviceIdentifyResponseHolder
{
    public DeviceIdentifyResponseHolder()
    {
    }
    public DeviceIdentifyResponseHolder(DeviceIdentifyResponse value)
    {
        this.value = value;
    }

    public DeviceIdentifyResponse value;
}
