// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/noahyang/deviceIdentify.jce'
// **********************************************************************

package com.qq.jce.DEVICE_IDENTIFY_SVR;

public final class IconDetails extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "DEVICE_IDENTIFY_SVR.IconDetails";
    }

    public String fullClassName()
    {
        return "com.qq.jce.DEVICE_IDENTIFY_SVR.IconDetails";
    }

    public String sIconPath = "";

    public String sIconSize = "";

    public String getSIconPath()
    {
        return sIconPath;
    }

    public void  setSIconPath(String sIconPath)
    {
        this.sIconPath = sIconPath;
    }

    public String getSIconSize()
    {
        return sIconSize;
    }

    public void  setSIconSize(String sIconSize)
    {
        this.sIconSize = sIconSize;
    }

    public IconDetails()
    {
    }

    public IconDetails(String sIconPath, String sIconSize)
    {
        this.sIconPath = sIconPath;
        this.sIconSize = sIconSize;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        IconDetails t = (IconDetails) o;
        return (
            com.qq.taf.jce.JceUtil.equals(sIconPath, t.sIconPath) && 
            com.qq.taf.jce.JceUtil.equals(sIconSize, t.sIconSize) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(sIconPath, 0);
        _os.write(sIconSize, 1);
    }


    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.sIconPath =  _is.readString(0, true);
        this.sIconSize =  _is.readString(1, true);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(sIconPath, "sIconPath");
        _ds.display(sIconSize, "sIconSize");
    }

    public void displaySimple(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.displaySimple(sIconPath, true);
        _ds.displaySimple(sIconSize, false);
    }

}

