// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/noahyang/you.jce'
// **********************************************************************

package com.qq.jce.MAAccess;

public final class AccessRspHead extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "MAAccess.AccessRspHead";
    }

    public String fullClassName()
    {
        return "com.qq.jce.MAAccess.AccessRspHead";
    }

    public int requestId = 0;

    public String cmd = "";

    public int ret = 0;

    public int getRequestId()
    {
        return requestId;
    }

    public void  setRequestId(int requestId)
    {
        this.requestId = requestId;
    }

    public String getCmd()
    {
        return cmd;
    }

    public void  setCmd(String cmd)
    {
        this.cmd = cmd;
    }

    public int getRet()
    {
        return ret;
    }

    public void  setRet(int ret)
    {
        this.ret = ret;
    }

    public AccessRspHead()
    {
    }

    public AccessRspHead(int requestId, String cmd, int ret)
    {
        this.requestId = requestId;
        this.cmd = cmd;
        this.ret = ret;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        AccessRspHead t = (AccessRspHead) o;
        return (
            com.qq.taf.jce.JceUtil.equals(requestId, t.requestId) && 
            com.qq.taf.jce.JceUtil.equals(cmd, t.cmd) && 
            com.qq.taf.jce.JceUtil.equals(ret, t.ret) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(requestId, 0);
        _os.write(cmd, 1);
        _os.write(ret, 4);
    }


    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.requestId = (int) _is.read(requestId, 0, true);
        this.cmd =  _is.readString(1, true);
        this.ret = (int) _is.read(ret, 4, true);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(requestId, "requestId");
        _ds.display(cmd, "cmd");
        _ds.display(ret, "ret");
    }

    public void displaySimple(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.displaySimple(requestId, true);
        _ds.displaySimple(cmd, true);
        _ds.displaySimple(ret, false);
    }

}

