// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/noahyang/you.jce'
// **********************************************************************

package com.qq.jce.MAAccess;

public final class AccessRequest extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "MAAccess.AccessRequest";
    }

    public String fullClassName()
    {
        return "com.qq.jce.MAAccess.AccessRequest";
    }

    public com.qq.jce.MAAccess.AccessReqHead head = null;

    public byte [] body = null;

    public com.qq.jce.MAAccess.AccessReqHead getHead()
    {
        return head;
    }

    public void  setHead(com.qq.jce.MAAccess.AccessReqHead head)
    {
        this.head = head;
    }

    public byte [] getBody()
    {
        return body;
    }

    public void  setBody(byte [] body)
    {
        this.body = body;
    }

    public AccessRequest()
    {
    }

    public AccessRequest(com.qq.jce.MAAccess.AccessReqHead head, byte [] body)
    {
        this.head = head;
        this.body = body;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        AccessRequest t = (AccessRequest) o;
        return (
            com.qq.taf.jce.JceUtil.equals(head, t.head) && 
            com.qq.taf.jce.JceUtil.equals(body, t.body) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(head, 0);
        if (null != body)
        {
            _os.write(body, 1);
        }
    }

    static com.qq.jce.MAAccess.AccessReqHead cache_head;
    static byte [] cache_body;

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        if(null == cache_head)
        {
            cache_head = new com.qq.jce.MAAccess.AccessReqHead();
        }
        this.head = (com.qq.jce.MAAccess.AccessReqHead) _is.read(cache_head, 0, true);
        if(null == cache_body)
        {
            cache_body = (byte[]) new byte[1];
            byte __var_7 = 0;
            ((byte[])cache_body)[0] = __var_7;
        }
        this.body = (byte []) _is.read(cache_body, 1, false);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(head, "head");
        _ds.display(body, "body");
    }

    public void displaySimple(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.displaySimple(head, true);
        _ds.displaySimple(body, false);
    }

}

