// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/noahyang/you.jce'
// **********************************************************************

package com.qq.jce.MAAccess;

public final class AddTapAppReq extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "MAAccess.AddTapAppReq";
    }

    public String fullClassName()
    {
        return "com.qq.jce.MAAccess.AddTapAppReq";
    }

    public String uid = "";

    public com.qq.jce.MAAccess.TapAppInfo stTapAppInfo = null;

    public String getUid()
    {
        return uid;
    }

    public void  setUid(String uid)
    {
        this.uid = uid;
    }

    public com.qq.jce.MAAccess.TapAppInfo getStTapAppInfo()
    {
        return stTapAppInfo;
    }

    public void  setStTapAppInfo(com.qq.jce.MAAccess.TapAppInfo stTapAppInfo)
    {
        this.stTapAppInfo = stTapAppInfo;
    }

    public AddTapAppReq()
    {
    }

    public AddTapAppReq(String uid, com.qq.jce.MAAccess.TapAppInfo stTapAppInfo)
    {
        this.uid = uid;
        this.stTapAppInfo = stTapAppInfo;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        AddTapAppReq t = (AddTapAppReq) o;
        return (
            com.qq.taf.jce.JceUtil.equals(uid, t.uid) && 
            com.qq.taf.jce.JceUtil.equals(stTapAppInfo, t.stTapAppInfo) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(uid, 0);
        _os.write(stTapAppInfo, 1);
    }

    static com.qq.jce.MAAccess.TapAppInfo cache_stTapAppInfo;

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.uid =  _is.readString(0, true);
        if(null == cache_stTapAppInfo)
        {
            cache_stTapAppInfo = new com.qq.jce.MAAccess.TapAppInfo();
        }
        this.stTapAppInfo = (com.qq.jce.MAAccess.TapAppInfo) _is.read(cache_stTapAppInfo, 1, true);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(uid, "uid");
        _ds.display(stTapAppInfo, "stTapAppInfo");
    }

    public void displaySimple(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.displaySimple(uid, true);
        _ds.displaySimple(stTapAppInfo, false);
    }

}

