// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/noahyang/you.jce'
// **********************************************************************

package com.qq.jce.MAAccess;

public final class ClaimTapAppReq extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "MAAccess.ClaimTapAppReq";
    }

    public String fullClassName()
    {
        return "com.qq.jce.MAAccess.ClaimTapAppReq";
    }

    public String packageName = "";

    public String signature = "";

    public String author = "";

    public long tapcpid = 0;

    public int iType = 0;

    public String getPackageName()
    {
        return packageName;
    }

    public void  setPackageName(String packageName)
    {
        this.packageName = packageName;
    }

    public String getSignature()
    {
        return signature;
    }

    public void  setSignature(String signature)
    {
        this.signature = signature;
    }

    public String getAuthor()
    {
        return author;
    }

    public void  setAuthor(String author)
    {
        this.author = author;
    }

    public long getTapcpid()
    {
        return tapcpid;
    }

    public void  setTapcpid(long tapcpid)
    {
        this.tapcpid = tapcpid;
    }

    public int getIType()
    {
        return iType;
    }

    public void  setIType(int iType)
    {
        this.iType = iType;
    }

    public ClaimTapAppReq()
    {
    }

    public ClaimTapAppReq(String packageName, String signature, String author, long tapcpid, int iType)
    {
        this.packageName = packageName;
        this.signature = signature;
        this.author = author;
        this.tapcpid = tapcpid;
        this.iType = iType;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        ClaimTapAppReq t = (ClaimTapAppReq) o;
        return (
            com.qq.taf.jce.JceUtil.equals(packageName, t.packageName) && 
            com.qq.taf.jce.JceUtil.equals(signature, t.signature) && 
            com.qq.taf.jce.JceUtil.equals(author, t.author) && 
            com.qq.taf.jce.JceUtil.equals(tapcpid, t.tapcpid) && 
            com.qq.taf.jce.JceUtil.equals(iType, t.iType) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(packageName, 0);
        _os.write(signature, 1);
        _os.write(author, 2);
        _os.write(tapcpid, 3);
        _os.write(iType, 4);
    }


    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.packageName =  _is.readString(0, true);
        this.signature =  _is.readString(1, true);
        this.author =  _is.readString(2, true);
        this.tapcpid = (long) _is.read(tapcpid, 3, true);
        this.iType = (int) _is.read(iType, 4, false);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(packageName, "packageName");
        _ds.display(signature, "signature");
        _ds.display(author, "author");
        _ds.display(tapcpid, "tapcpid");
        _ds.display(iType, "iType");
    }

    public void displaySimple(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.displaySimple(packageName, true);
        _ds.displaySimple(signature, true);
        _ds.displaySimple(author, true);
        _ds.displaySimple(tapcpid, true);
        _ds.displaySimple(iType, false);
    }

}

