// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/noahyang/you.jce'
// **********************************************************************

package com.qq.jce.MAAccess;

public final class GetAppDetailBatchRsp extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "MAAccess.GetAppDetailBatchRsp";
    }

    public String fullClassName()
    {
        return "com.qq.jce.MAAccess.GetAppDetailBatchRsp";
    }

    public int ret = 0;

    public java.util.Map<String, com.qq.jce.MAAccess.AppDetail> mpRes = null;

    public int getRet()
    {
        return ret;
    }

    public void  setRet(int ret)
    {
        this.ret = ret;
    }

    public java.util.Map<String, com.qq.jce.MAAccess.AppDetail> getMpRes()
    {
        return mpRes;
    }

    public void  setMpRes(java.util.Map<String, com.qq.jce.MAAccess.AppDetail> mpRes)
    {
        this.mpRes = mpRes;
    }

    public GetAppDetailBatchRsp()
    {
    }

    public GetAppDetailBatchRsp(int ret, java.util.Map<String, com.qq.jce.MAAccess.AppDetail> mpRes)
    {
        this.ret = ret;
        this.mpRes = mpRes;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        GetAppDetailBatchRsp t = (GetAppDetailBatchRsp) o;
        return (
            com.qq.taf.jce.JceUtil.equals(ret, t.ret) && 
            com.qq.taf.jce.JceUtil.equals(mpRes, t.mpRes) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(ret, 0);
        _os.write(mpRes, 1);
    }

    static java.util.Map<String, com.qq.jce.MAAccess.AppDetail> cache_mpRes;

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.ret = (int) _is.read(ret, 0, true);
        if(null == cache_mpRes)
        {
            cache_mpRes = new java.util.HashMap<String, com.qq.jce.MAAccess.AppDetail>();
            String __var_13 = "";
            com.qq.jce.MAAccess.AppDetail __var_14 = new com.qq.jce.MAAccess.AppDetail();
            cache_mpRes.put(__var_13, __var_14);
        }
        this.mpRes = (java.util.Map<String, com.qq.jce.MAAccess.AppDetail>) _is.read(cache_mpRes, 1, true);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(ret, "ret");
        _ds.display(mpRes, "mpRes");
    }

    public void displaySimple(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.displaySimple(ret, true);
        _ds.displaySimple(mpRes, false);
    }

}

