// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/noahyang/you.jce'
// **********************************************************************

package com.qq.jce.MAAccess;

public final class GetAppUpdateRsp extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "MAAccess.GetAppUpdateRsp";
    }

    public String fullClassName()
    {
        return "com.qq.jce.MAAccess.GetAppUpdateRsp";
    }

    public int ret = 0;

    public java.util.ArrayList<com.qq.jce.MAAccess.AppUpdateInfo> appUpdateInfoList = null;

    public int getRet()
    {
        return ret;
    }

    public void  setRet(int ret)
    {
        this.ret = ret;
    }

    public java.util.ArrayList<com.qq.jce.MAAccess.AppUpdateInfo> getAppUpdateInfoList()
    {
        return appUpdateInfoList;
    }

    public void  setAppUpdateInfoList(java.util.ArrayList<com.qq.jce.MAAccess.AppUpdateInfo> appUpdateInfoList)
    {
        this.appUpdateInfoList = appUpdateInfoList;
    }

    public GetAppUpdateRsp()
    {
    }

    public GetAppUpdateRsp(int ret, java.util.ArrayList<com.qq.jce.MAAccess.AppUpdateInfo> appUpdateInfoList)
    {
        this.ret = ret;
        this.appUpdateInfoList = appUpdateInfoList;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        GetAppUpdateRsp t = (GetAppUpdateRsp) o;
        return (
            com.qq.taf.jce.JceUtil.equals(ret, t.ret) && 
            com.qq.taf.jce.JceUtil.equals(appUpdateInfoList, t.appUpdateInfoList) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(ret, 0);
        _os.write(appUpdateInfoList, 1);
    }

    static java.util.ArrayList<com.qq.jce.MAAccess.AppUpdateInfo> cache_appUpdateInfoList;

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.ret = (int) _is.read(ret, 0, true);
        if(null == cache_appUpdateInfoList)
        {
            cache_appUpdateInfoList = new java.util.ArrayList<com.qq.jce.MAAccess.AppUpdateInfo>();
            com.qq.jce.MAAccess.AppUpdateInfo __var_33 = new com.qq.jce.MAAccess.AppUpdateInfo();
            ((java.util.ArrayList<com.qq.jce.MAAccess.AppUpdateInfo>)cache_appUpdateInfoList).add(__var_33);
        }
        this.appUpdateInfoList = (java.util.ArrayList<com.qq.jce.MAAccess.AppUpdateInfo>) _is.read(cache_appUpdateInfoList, 1, true);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(ret, "ret");
        _ds.display(appUpdateInfoList, "appUpdateInfoList");
    }

    public void displaySimple(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.displaySimple(ret, true);
        _ds.displaySimple(appUpdateInfoList, false);
    }

}

