// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/noahyang/you.jce'
// **********************************************************************

package com.qq.jce.MAAccess;

public final class GetTapAppStatusByUidReq extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "MAAccess.GetTapAppStatusByUidReq";
    }

    public String fullClassName()
    {
        return "com.qq.jce.MAAccess.GetTapAppStatusByUidReq";
    }

    public String uid = "";

    public String getUid()
    {
        return uid;
    }

    public void  setUid(String uid)
    {
        this.uid = uid;
    }

    public GetTapAppStatusByUidReq()
    {
    }

    public GetTapAppStatusByUidReq(String uid)
    {
        this.uid = uid;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        GetTapAppStatusByUidReq t = (GetTapAppStatusByUidReq) o;
        return (
            com.qq.taf.jce.JceUtil.equals(uid, t.uid) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(uid, 0);
    }


    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.uid =  _is.readString(0, true);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(uid, "uid");
    }

    public void displaySimple(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.displaySimple(uid, false);
    }

}

