// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/noahyang/you.jce'
// **********************************************************************

package com.qq.jce.MAAccess;

public final class PicInfoHolder
{
    public PicInfoHolder()
    {
    }
    public PicInfoHolder(PicInfo value)
    {
        this.value = value;
    }

    public PicInfo value;
}
