// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/noahyang/you.jce'
// **********************************************************************

package com.qq.jce.MAAccess;

public final class SetWhiteListRsp extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "MAAccess.SetWhiteListRsp";
    }

    public String fullClassName()
    {
        return "com.qq.jce.MAAccess.SetWhiteListRsp";
    }

    public int ret = 0;

    public String openId = "";

    public long uin = 0;

    public int getRet()
    {
        return ret;
    }

    public void  setRet(int ret)
    {
        this.ret = ret;
    }

    public String getOpenId()
    {
        return openId;
    }

    public void  setOpenId(String openId)
    {
        this.openId = openId;
    }

    public long getUin()
    {
        return uin;
    }

    public void  setUin(long uin)
    {
        this.uin = uin;
    }

    public SetWhiteListRsp()
    {
    }

    public SetWhiteListRsp(int ret, String openId, long uin)
    {
        this.ret = ret;
        this.openId = openId;
        this.uin = uin;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        SetWhiteListRsp t = (SetWhiteListRsp) o;
        return (
            com.qq.taf.jce.JceUtil.equals(ret, t.ret) && 
            com.qq.taf.jce.JceUtil.equals(openId, t.openId) && 
            com.qq.taf.jce.JceUtil.equals(uin, t.uin) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(ret, 0);
        if (null != openId)
        {
            _os.write(openId, 1);
        }
        _os.write(uin, 2);
    }


    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.ret = (int) _is.read(ret, 0, false);
        this.openId =  _is.readString(1, false);
        this.uin = (long) _is.read(uin, 2, false);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(ret, "ret");
        _ds.display(openId, "openId");
        _ds.display(uin, "uin");
    }

    public void displaySimple(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.displaySimple(ret, true);
        _ds.displaySimple(openId, true);
        _ds.displaySimple(uin, false);
    }

}

