// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/noahyang/you.jce'
// **********************************************************************

package com.qq.jce.MAAccess;

public final class TapAppInfo extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "MAAccess.TapAppInfo";
    }

    public String fullClassName()
    {
        return "com.qq.jce.MAAccess.TapAppInfo";
    }

    public String packageName = "";

    public String appName = "";

    public String englishName = "";

    public int isSelfDev = 0;

    public String categoryName = "";

    public int categoryId = 0;

    public long fileSize = 0;

    public String apkMd5 = "";

    public String signature = "";

    public String author = "";

    public int versionCode = 0;

    public String versionName = "";

    public String sDesc = "";

    public int lang = 0;

    public String logo = "";

    public String snapshot = "";

    public String url = "";

    public int feepolicy = 0;

    public byte isOfficial = 0;

    public int publishTime = 0;

    public String keyword = "";

    public String screenSize = "";

    public String terminal = "";

    public long lTapCpid = 0;

    public String newFeature = "";

    public String getPackageName()
    {
        return packageName;
    }

    public void  setPackageName(String packageName)
    {
        this.packageName = packageName;
    }

    public String getAppName()
    {
        return appName;
    }

    public void  setAppName(String appName)
    {
        this.appName = appName;
    }

    public String getEnglishName()
    {
        return englishName;
    }

    public void  setEnglishName(String englishName)
    {
        this.englishName = englishName;
    }

    public int getIsSelfDev()
    {
        return isSelfDev;
    }

    public void  setIsSelfDev(int isSelfDev)
    {
        this.isSelfDev = isSelfDev;
    }

    public String getCategoryName()
    {
        return categoryName;
    }

    public void  setCategoryName(String categoryName)
    {
        this.categoryName = categoryName;
    }

    public int getCategoryId()
    {
        return categoryId;
    }

    public void  setCategoryId(int categoryId)
    {
        this.categoryId = categoryId;
    }

    public long getFileSize()
    {
        return fileSize;
    }

    public void  setFileSize(long fileSize)
    {
        this.fileSize = fileSize;
    }

    public String getApkMd5()
    {
        return apkMd5;
    }

    public void  setApkMd5(String apkMd5)
    {
        this.apkMd5 = apkMd5;
    }

    public String getSignature()
    {
        return signature;
    }

    public void  setSignature(String signature)
    {
        this.signature = signature;
    }

    public String getAuthor()
    {
        return author;
    }

    public void  setAuthor(String author)
    {
        this.author = author;
    }

    public int getVersionCode()
    {
        return versionCode;
    }

    public void  setVersionCode(int versionCode)
    {
        this.versionCode = versionCode;
    }

    public String getVersionName()
    {
        return versionName;
    }

    public void  setVersionName(String versionName)
    {
        this.versionName = versionName;
    }

    public String getSDesc()
    {
        return sDesc;
    }

    public void  setSDesc(String sDesc)
    {
        this.sDesc = sDesc;
    }

    public int getLang()
    {
        return lang;
    }

    public void  setLang(int lang)
    {
        this.lang = lang;
    }

    public String getLogo()
    {
        return logo;
    }

    public void  setLogo(String logo)
    {
        this.logo = logo;
    }

    public String getSnapshot()
    {
        return snapshot;
    }

    public void  setSnapshot(String snapshot)
    {
        this.snapshot = snapshot;
    }

    public String getUrl()
    {
        return url;
    }

    public void  setUrl(String url)
    {
        this.url = url;
    }

    public int getFeepolicy()
    {
        return feepolicy;
    }

    public void  setFeepolicy(int feepolicy)
    {
        this.feepolicy = feepolicy;
    }

    public byte getIsOfficial()
    {
        return isOfficial;
    }

    public void  setIsOfficial(byte isOfficial)
    {
        this.isOfficial = isOfficial;
    }

    public int getPublishTime()
    {
        return publishTime;
    }

    public void  setPublishTime(int publishTime)
    {
        this.publishTime = publishTime;
    }

    public String getKeyword()
    {
        return keyword;
    }

    public void  setKeyword(String keyword)
    {
        this.keyword = keyword;
    }

    public String getScreenSize()
    {
        return screenSize;
    }

    public void  setScreenSize(String screenSize)
    {
        this.screenSize = screenSize;
    }

    public String getTerminal()
    {
        return terminal;
    }

    public void  setTerminal(String terminal)
    {
        this.terminal = terminal;
    }

    public long getLTapCpid()
    {
        return lTapCpid;
    }

    public void  setLTapCpid(long lTapCpid)
    {
        this.lTapCpid = lTapCpid;
    }

    public String getNewFeature()
    {
        return newFeature;
    }

    public void  setNewFeature(String newFeature)
    {
        this.newFeature = newFeature;
    }

    public TapAppInfo()
    {
    }

    public TapAppInfo(String packageName, String appName, String englishName, int isSelfDev, String categoryName, int categoryId, long fileSize, String apkMd5, String signature, String author, int versionCode, String versionName, String sDesc, int lang, String logo, String snapshot, String url, int feepolicy, byte isOfficial, int publishTime, String keyword, String screenSize, String terminal, long lTapCpid, String newFeature)
    {
        this.packageName = packageName;
        this.appName = appName;
        this.englishName = englishName;
        this.isSelfDev = isSelfDev;
        this.categoryName = categoryName;
        this.categoryId = categoryId;
        this.fileSize = fileSize;
        this.apkMd5 = apkMd5;
        this.signature = signature;
        this.author = author;
        this.versionCode = versionCode;
        this.versionName = versionName;
        this.sDesc = sDesc;
        this.lang = lang;
        this.logo = logo;
        this.snapshot = snapshot;
        this.url = url;
        this.feepolicy = feepolicy;
        this.isOfficial = isOfficial;
        this.publishTime = publishTime;
        this.keyword = keyword;
        this.screenSize = screenSize;
        this.terminal = terminal;
        this.lTapCpid = lTapCpid;
        this.newFeature = newFeature;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        TapAppInfo t = (TapAppInfo) o;
        return (
            com.qq.taf.jce.JceUtil.equals(packageName, t.packageName) && 
            com.qq.taf.jce.JceUtil.equals(appName, t.appName) && 
            com.qq.taf.jce.JceUtil.equals(englishName, t.englishName) && 
            com.qq.taf.jce.JceUtil.equals(isSelfDev, t.isSelfDev) && 
            com.qq.taf.jce.JceUtil.equals(categoryName, t.categoryName) && 
            com.qq.taf.jce.JceUtil.equals(categoryId, t.categoryId) && 
            com.qq.taf.jce.JceUtil.equals(fileSize, t.fileSize) && 
            com.qq.taf.jce.JceUtil.equals(apkMd5, t.apkMd5) && 
            com.qq.taf.jce.JceUtil.equals(signature, t.signature) && 
            com.qq.taf.jce.JceUtil.equals(author, t.author) && 
            com.qq.taf.jce.JceUtil.equals(versionCode, t.versionCode) && 
            com.qq.taf.jce.JceUtil.equals(versionName, t.versionName) && 
            com.qq.taf.jce.JceUtil.equals(sDesc, t.sDesc) && 
            com.qq.taf.jce.JceUtil.equals(lang, t.lang) && 
            com.qq.taf.jce.JceUtil.equals(logo, t.logo) && 
            com.qq.taf.jce.JceUtil.equals(snapshot, t.snapshot) && 
            com.qq.taf.jce.JceUtil.equals(url, t.url) && 
            com.qq.taf.jce.JceUtil.equals(feepolicy, t.feepolicy) && 
            com.qq.taf.jce.JceUtil.equals(isOfficial, t.isOfficial) && 
            com.qq.taf.jce.JceUtil.equals(publishTime, t.publishTime) && 
            com.qq.taf.jce.JceUtil.equals(keyword, t.keyword) && 
            com.qq.taf.jce.JceUtil.equals(screenSize, t.screenSize) && 
            com.qq.taf.jce.JceUtil.equals(terminal, t.terminal) && 
            com.qq.taf.jce.JceUtil.equals(lTapCpid, t.lTapCpid) && 
            com.qq.taf.jce.JceUtil.equals(newFeature, t.newFeature) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(packageName, 0);
        _os.write(appName, 1);
        _os.write(englishName, 2);
        _os.write(isSelfDev, 3);
        _os.write(categoryName, 4);
        _os.write(categoryId, 5);
        _os.write(fileSize, 6);
        _os.write(apkMd5, 7);
        _os.write(signature, 8);
        _os.write(author, 9);
        _os.write(versionCode, 10);
        _os.write(versionName, 11);
        _os.write(sDesc, 12);
        _os.write(lang, 13);
        _os.write(logo, 14);
        _os.write(snapshot, 15);
        _os.write(url, 16);
        _os.write(feepolicy, 17);
        _os.write(isOfficial, 18);
        _os.write(publishTime, 19);
        _os.write(keyword, 20);
        if (null != screenSize)
        {
            _os.write(screenSize, 21);
        }
        if (null != terminal)
        {
            _os.write(terminal, 22);
        }
        _os.write(lTapCpid, 23);
        if (null != newFeature)
        {
            _os.write(newFeature, 24);
        }
    }


    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.packageName =  _is.readString(0, true);
        this.appName =  _is.readString(1, true);
        this.englishName =  _is.readString(2, true);
        this.isSelfDev = (int) _is.read(isSelfDev, 3, true);
        this.categoryName =  _is.readString(4, true);
        this.categoryId = (int) _is.read(categoryId, 5, true);
        this.fileSize = (long) _is.read(fileSize, 6, true);
        this.apkMd5 =  _is.readString(7, true);
        this.signature =  _is.readString(8, true);
        this.author =  _is.readString(9, true);
        this.versionCode = (int) _is.read(versionCode, 10, true);
        this.versionName =  _is.readString(11, true);
        this.sDesc =  _is.readString(12, true);
        this.lang = (int) _is.read(lang, 13, true);
        this.logo =  _is.readString(14, true);
        this.snapshot =  _is.readString(15, true);
        this.url =  _is.readString(16, true);
        this.feepolicy = (int) _is.read(feepolicy, 17, true);
        this.isOfficial = (byte) _is.read(isOfficial, 18, true);
        this.publishTime = (int) _is.read(publishTime, 19, true);
        this.keyword =  _is.readString(20, true);
        this.screenSize =  _is.readString(21, false);
        this.terminal =  _is.readString(22, false);
        this.lTapCpid = (long) _is.read(lTapCpid, 23, false);
        this.newFeature =  _is.readString(24, false);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(packageName, "packageName");
        _ds.display(appName, "appName");
        _ds.display(englishName, "englishName");
        _ds.display(isSelfDev, "isSelfDev");
        _ds.display(categoryName, "categoryName");
        _ds.display(categoryId, "categoryId");
        _ds.display(fileSize, "fileSize");
        _ds.display(apkMd5, "apkMd5");
        _ds.display(signature, "signature");
        _ds.display(author, "author");
        _ds.display(versionCode, "versionCode");
        _ds.display(versionName, "versionName");
        _ds.display(sDesc, "sDesc");
        _ds.display(lang, "lang");
        _ds.display(logo, "logo");
        _ds.display(snapshot, "snapshot");
        _ds.display(url, "url");
        _ds.display(feepolicy, "feepolicy");
        _ds.display(isOfficial, "isOfficial");
        _ds.display(publishTime, "publishTime");
        _ds.display(keyword, "keyword");
        _ds.display(screenSize, "screenSize");
        _ds.display(terminal, "terminal");
        _ds.display(lTapCpid, "lTapCpid");
        _ds.display(newFeature, "newFeature");
    }

    public void displaySimple(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.displaySimple(packageName, true);
        _ds.displaySimple(appName, true);
        _ds.displaySimple(englishName, true);
        _ds.displaySimple(isSelfDev, true);
        _ds.displaySimple(categoryName, true);
        _ds.displaySimple(categoryId, true);
        _ds.displaySimple(fileSize, true);
        _ds.displaySimple(apkMd5, true);
        _ds.displaySimple(signature, true);
        _ds.displaySimple(author, true);
        _ds.displaySimple(versionCode, true);
        _ds.displaySimple(versionName, true);
        _ds.displaySimple(sDesc, true);
        _ds.displaySimple(lang, true);
        _ds.displaySimple(logo, true);
        _ds.displaySimple(snapshot, true);
        _ds.displaySimple(url, true);
        _ds.displaySimple(feepolicy, true);
        _ds.displaySimple(isOfficial, true);
        _ds.displaySimple(publishTime, true);
        _ds.displaySimple(keyword, true);
        _ds.displaySimple(screenSize, true);
        _ds.displaySimple(terminal, true);
        _ds.displaySimple(lTapCpid, true);
        _ds.displaySimple(newFeature, false);
    }

}

