// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/noahyang/kvConfig.jce'
// **********************************************************************

package com.qq.jce.KV_CONFIG;

public final class key_type implements java.io.Serializable
{
    private static key_type[] __values = new key_type[2];
    private int __value;
    private String __T = new String();

    public static final int _key_type_delete = 1;
    public static final key_type key_type_delete = new key_type(0,_key_type_delete,"key_type_delete");
    public static final int _key_type_update = 2;
    public static final key_type key_type_update = new key_type(1,_key_type_update,"key_type_update");

    public static key_type convert(int val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].value() == val)
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public static key_type convert(String val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].toString().equals(val))
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public int value()
    {
        return __value;
    }

    public String toString()
    {
        return __T;
    }

    private key_type(int index, int val, String s)
    {
        __T = s;
        __value = val;
        __values[index] = this;
    }

}
