// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/noahyang/kvConfig.jce'
// **********************************************************************

package com.qq.jce.KV_CONFIG;

public final class query_kv_response extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "KV_CONFIG.query_kv_response";
    }

    public String fullClassName()
    {
        return "com.qq.jce.KV_CONFIG.query_kv_response";
    }

    public int ret_code = 0;

    public String err_msg = "";

    public java.util.ArrayList<com.qq.jce.KV_CONFIG.kv_content> kv_list = null;

    public int getRet_code()
    {
        return ret_code;
    }

    public void  setRet_code(int ret_code)
    {
        this.ret_code = ret_code;
    }

    public String getErr_msg()
    {
        return err_msg;
    }

    public void  setErr_msg(String err_msg)
    {
        this.err_msg = err_msg;
    }

    public java.util.ArrayList<com.qq.jce.KV_CONFIG.kv_content> getKv_list()
    {
        return kv_list;
    }

    public void  setKv_list(java.util.ArrayList<com.qq.jce.KV_CONFIG.kv_content> kv_list)
    {
        this.kv_list = kv_list;
    }

    public query_kv_response()
    {
    }

    public query_kv_response(int ret_code, String err_msg, java.util.ArrayList<com.qq.jce.KV_CONFIG.kv_content> kv_list)
    {
        this.ret_code = ret_code;
        this.err_msg = err_msg;
        this.kv_list = kv_list;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        query_kv_response t = (query_kv_response) o;
        return (
            com.qq.taf.jce.JceUtil.equals(ret_code, t.ret_code) && 
            com.qq.taf.jce.JceUtil.equals(err_msg, t.err_msg) && 
            com.qq.taf.jce.JceUtil.equals(kv_list, t.kv_list) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(ret_code, 0);
        if (null != err_msg)
        {
            _os.write(err_msg, 1);
        }
        if (null != kv_list)
        {
            _os.write(kv_list, 2);
        }
    }

    static int cache_ret_code;
    static java.util.ArrayList<com.qq.jce.KV_CONFIG.kv_content> cache_kv_list;

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.ret_code = (int) _is.read(ret_code, 0, true);
        this.err_msg =  _is.readString(1, false);
        if(null == cache_kv_list)
        {
            cache_kv_list = new java.util.ArrayList<com.qq.jce.KV_CONFIG.kv_content>();
            com.qq.jce.KV_CONFIG.kv_content __var_1 = new com.qq.jce.KV_CONFIG.kv_content();
            ((java.util.ArrayList<com.qq.jce.KV_CONFIG.kv_content>)cache_kv_list).add(__var_1);
        }
        this.kv_list = (java.util.ArrayList<com.qq.jce.KV_CONFIG.kv_content>) _is.read(cache_kv_list, 2, false);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(ret_code, "ret_code");
        _ds.display(err_msg, "err_msg");
        _ds.display(kv_list, "kv_list");
    }

    public void displaySimple(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.displaySimple(ret_code, true);
        _ds.displaySimple(err_msg, true);
        _ds.displaySimple(kv_list, false);
    }

}

