// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/noahyang/kvConfig.jce'
// **********************************************************************

package com.qq.jce.KV_CONFIG;

public final class set_kv_responseHolder
{
    public set_kv_responseHolder()
    {
    }
    public set_kv_responseHolder(set_kv_response value)
    {
        this.value = value;
    }

    public set_kv_response value;
}
