// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/noahyang/deviceDriver.jce'
// **********************************************************************

package com.qq.jce.DEVICE_DRIVER_SVR;

public final class ConnDeviceDriverRequest extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "DEVICE_DRIVER_SVR.ConnDeviceDriverRequest";
    }

    public String fullClassName()
    {
        return "com.qq.jce.DEVICE_DRIVER_SVR.ConnDeviceDriverRequest";
    }

    public String sPCID = "";

    public String sVID = "";

    public String sPID = "";

    public String sDeviceName = "";

    public int eOSVer = 0;

    public int eOSBits = 0;

    public boolean bCommon = true;

    public String getSPCID()
    {
        return sPCID;
    }

    public void  setSPCID(String sPCID)
    {
        this.sPCID = sPCID;
    }

    public String getSVID()
    {
        return sVID;
    }

    public void  setSVID(String sVID)
    {
        this.sVID = sVID;
    }

    public String getSPID()
    {
        return sPID;
    }

    public void  setSPID(String sPID)
    {
        this.sPID = sPID;
    }

    public String getSDeviceName()
    {
        return sDeviceName;
    }

    public void  setSDeviceName(String sDeviceName)
    {
        this.sDeviceName = sDeviceName;
    }

    public int getEOSVer()
    {
        return eOSVer;
    }

    public void  setEOSVer(int eOSVer)
    {
        this.eOSVer = eOSVer;
    }

    public int getEOSBits()
    {
        return eOSBits;
    }

    public void  setEOSBits(int eOSBits)
    {
        this.eOSBits = eOSBits;
    }

    public boolean getBCommon()
    {
        return bCommon;
    }

    public void  setBCommon(boolean bCommon)
    {
        this.bCommon = bCommon;
    }

    public ConnDeviceDriverRequest()
    {
    }

    public ConnDeviceDriverRequest(String sPCID, String sVID, String sPID, String sDeviceName, int eOSVer, int eOSBits, boolean bCommon)
    {
        this.sPCID = sPCID;
        this.sVID = sVID;
        this.sPID = sPID;
        this.sDeviceName = sDeviceName;
        this.eOSVer = eOSVer;
        this.eOSBits = eOSBits;
        this.bCommon = bCommon;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        ConnDeviceDriverRequest t = (ConnDeviceDriverRequest) o;
        return (
            com.qq.taf.jce.JceUtil.equals(sPCID, t.sPCID) && 
            com.qq.taf.jce.JceUtil.equals(sVID, t.sVID) && 
            com.qq.taf.jce.JceUtil.equals(sPID, t.sPID) && 
            com.qq.taf.jce.JceUtil.equals(sDeviceName, t.sDeviceName) && 
            com.qq.taf.jce.JceUtil.equals(eOSVer, t.eOSVer) && 
            com.qq.taf.jce.JceUtil.equals(eOSBits, t.eOSBits) && 
            com.qq.taf.jce.JceUtil.equals(bCommon, t.bCommon) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(sPCID, 0);
        _os.write(sVID, 1);
        _os.write(sPID, 2);
        _os.write(sDeviceName, 3);
        _os.write(eOSVer, 4);
        _os.write(eOSBits, 5);
        _os.write(bCommon, 6);
    }

    static int cache_eOSVer;
    static int cache_eOSBits;

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.sPCID =  _is.readString(0, true);
        this.sVID =  _is.readString(1, true);
        this.sPID =  _is.readString(2, true);
        this.sDeviceName =  _is.readString(3, true);
        this.eOSVer = (int) _is.read(eOSVer, 4, true);
        this.eOSBits = (int) _is.read(eOSBits, 5, true);
        this.bCommon = (boolean) _is.read(bCommon, 6, true);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(sPCID, "sPCID");
        _ds.display(sVID, "sVID");
        _ds.display(sPID, "sPID");
        _ds.display(sDeviceName, "sDeviceName");
        _ds.display(eOSVer, "eOSVer");
        _ds.display(eOSBits, "eOSBits");
        _ds.display(bCommon, "bCommon");
    }

    public void displaySimple(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.displaySimple(sPCID, true);
        _ds.displaySimple(sVID, true);
        _ds.displaySimple(sPID, true);
        _ds.displaySimple(sDeviceName, true);
        _ds.displaySimple(eOSVer, true);
        _ds.displaySimple(eOSBits, true);
        _ds.displaySimple(bCommon, false);
    }

}

