// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/noahyang/deviceDriver.jce'
// **********************************************************************

package com.qq.jce.DEVICE_DRIVER_SVR;

public final class InterfaceType implements java.io.Serializable
{
    private static InterfaceType[] __values = new InterfaceType[3];
    private int __value;
    private String __T = new String();

    public static final int _IT_NORMAL = 0;
    public static final InterfaceType IT_NORMAL = new InterfaceType(0,_IT_NORMAL,"IT_NORMAL");
    public static final int _IT_REPAIR = 1;
    public static final InterfaceType IT_REPAIR = new InterfaceType(1,_IT_REPAIR,"IT_REPAIR");
    public static final int _IT_UNINSTALL = 2;
    public static final InterfaceType IT_UNINSTALL = new InterfaceType(2,_IT_UNINSTALL,"IT_UNINSTALL");

    public static InterfaceType convert(int val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].value() == val)
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public static InterfaceType convert(String val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].toString().equals(val))
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public int value()
    {
        return __value;
    }

    public String toString()
    {
        return __T;
    }

    private InterfaceType(int index, int val, String s)
    {
        __T = s;
        __value = val;
        __values[index] = this;
    }

}
