// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/noahyang/deviceDriver.jce'
// **********************************************************************

package com.qq.jce.DEVICE_DRIVER_SVR;

public final class OSBits implements java.io.Serializable
{
    private static OSBits[] __values = new OSBits[3];
    private int __value;
    private String __T = new String();

    public static final int _OB_COMMON = 0;
    public static final OSBits OB_COMMON = new OSBits(0,_OB_COMMON,"OB_COMMON");
    public static final int _OB_32 = 1;
    public static final OSBits OB_32 = new OSBits(1,_OB_32,"OB_32");
    public static final int _OB_64 = 2;
    public static final OSBits OB_64 = new OSBits(2,_OB_64,"OB_64");

    public static OSBits convert(int val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].value() == val)
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public static OSBits convert(String val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].toString().equals(val))
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public int value()
    {
        return __value;
    }

    public String toString()
    {
        return __T;
    }

    private OSBits(int index, int val, String s)
    {
        __T = s;
        __value = val;
        __values[index] = this;
    }

}
