// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/noahyang/ws.jce'
// **********************************************************************

package com.qq.jce.ws;

public final class DockMedicalTip extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "ws.DockMedicalTip";
    }

    public String fullClassName()
    {
        return "com.qq.jce.ws.DockMedicalTip";
    }

    public String type = "";

    public String description = "";

    public String jumpAddress = "";

    public String reserved = "";

    public String getType()
    {
        return type;
    }

    public void  setType(String type)
    {
        this.type = type;
    }

    public String getDescription()
    {
        return description;
    }

    public void  setDescription(String description)
    {
        this.description = description;
    }

    public String getJumpAddress()
    {
        return jumpAddress;
    }

    public void  setJumpAddress(String jumpAddress)
    {
        this.jumpAddress = jumpAddress;
    }

    public String getReserved()
    {
        return reserved;
    }

    public void  setReserved(String reserved)
    {
        this.reserved = reserved;
    }

    public DockMedicalTip()
    {
    }

    public DockMedicalTip(String type, String description, String jumpAddress, String reserved)
    {
        this.type = type;
        this.description = description;
        this.jumpAddress = jumpAddress;
        this.reserved = reserved;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        DockMedicalTip t = (DockMedicalTip) o;
        return (
            com.qq.taf.jce.JceUtil.equals(type, t.type) && 
            com.qq.taf.jce.JceUtil.equals(description, t.description) && 
            com.qq.taf.jce.JceUtil.equals(jumpAddress, t.jumpAddress) && 
            com.qq.taf.jce.JceUtil.equals(reserved, t.reserved) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(type, 0);
        _os.write(description, 1);
        _os.write(jumpAddress, 2);
        if (null != reserved)
        {
            _os.write(reserved, 3);
        }
    }


    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.type =  _is.readString(0, true);
        this.description =  _is.readString(1, true);
        this.jumpAddress =  _is.readString(2, true);
        this.reserved =  _is.readString(3, false);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(type, "type");
        _ds.display(description, "description");
        _ds.display(jumpAddress, "jumpAddress");
        _ds.display(reserved, "reserved");
    }

    public void displaySimple(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.displaySimple(type, true);
        _ds.displaySimple(description, true);
        _ds.displaySimple(jumpAddress, true);
        _ds.displaySimple(reserved, false);
    }

}

