// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/noahyang/ws.jce'
// **********************************************************************

package com.qq.jce.ws;

public final class DockSearchBox extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "ws.DockSearchBox";
    }

    public String fullClassName()
    {
        return "com.qq.jce.ws.DockSearchBox";
    }

    public String show = "";

    public String copywriting = "";

    public String searchUrl = "";

    public String reserved = "";

    public String getShow()
    {
        return show;
    }

    public void  setShow(String show)
    {
        this.show = show;
    }

    public String getCopywriting()
    {
        return copywriting;
    }

    public void  setCopywriting(String copywriting)
    {
        this.copywriting = copywriting;
    }

    public String getSearchUrl()
    {
        return searchUrl;
    }

    public void  setSearchUrl(String searchUrl)
    {
        this.searchUrl = searchUrl;
    }

    public String getReserved()
    {
        return reserved;
    }

    public void  setReserved(String reserved)
    {
        this.reserved = reserved;
    }

    public DockSearchBox()
    {
    }

    public DockSearchBox(String show, String copywriting, String searchUrl, String reserved)
    {
        this.show = show;
        this.copywriting = copywriting;
        this.searchUrl = searchUrl;
        this.reserved = reserved;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        DockSearchBox t = (DockSearchBox) o;
        return (
            com.qq.taf.jce.JceUtil.equals(show, t.show) && 
            com.qq.taf.jce.JceUtil.equals(copywriting, t.copywriting) && 
            com.qq.taf.jce.JceUtil.equals(searchUrl, t.searchUrl) && 
            com.qq.taf.jce.JceUtil.equals(reserved, t.reserved) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(show, 0);
        _os.write(copywriting, 1);
        _os.write(searchUrl, 2);
        if (null != reserved)
        {
            _os.write(reserved, 3);
        }
    }


    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.show =  _is.readString(0, true);
        this.copywriting =  _is.readString(1, true);
        this.searchUrl =  _is.readString(2, true);
        this.reserved =  _is.readString(3, false);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(show, "show");
        _ds.display(copywriting, "copywriting");
        _ds.display(searchUrl, "searchUrl");
        _ds.display(reserved, "reserved");
    }

    public void displaySimple(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.displaySimple(show, true);
        _ds.displaySimple(copywriting, true);
        _ds.displaySimple(searchUrl, true);
        _ds.displaySimple(reserved, false);
    }

}

