// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/noahyang/ws.jce'
// **********************************************************************

package com.qq.jce.ws;

public final class DockRecommandHolder
{
    public DockRecommandHolder()
    {
    }
    public DockRecommandHolder(DockRecommand value)
    {
        this.value = value;
    }

    public DockRecommand value;
}
