// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/noahyang/ws.jce'
// **********************************************************************

package com.qq.jce.ws;

public final class DockSearchHotWordGroup extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "ws.DockSearchHotWordGroup";
    }

    public String fullClassName()
    {
        return "com.qq.jce.ws.DockSearchHotWordGroup";
    }

    public String groupName = "";

    public java.util.ArrayList<com.qq.jce.ws.DockSearchHotWord> dockSearchHotWords = null;

    public String reserved = "";

    public String getGroupName()
    {
        return groupName;
    }

    public void  setGroupName(String groupName)
    {
        this.groupName = groupName;
    }

    public java.util.ArrayList<com.qq.jce.ws.DockSearchHotWord> getDockSearchHotWords()
    {
        return dockSearchHotWords;
    }

    public void  setDockSearchHotWords(java.util.ArrayList<com.qq.jce.ws.DockSearchHotWord> dockSearchHotWords)
    {
        this.dockSearchHotWords = dockSearchHotWords;
    }

    public String getReserved()
    {
        return reserved;
    }

    public void  setReserved(String reserved)
    {
        this.reserved = reserved;
    }

    public DockSearchHotWordGroup()
    {
    }

    public DockSearchHotWordGroup(String groupName, java.util.ArrayList<com.qq.jce.ws.DockSearchHotWord> dockSearchHotWords, String reserved)
    {
        this.groupName = groupName;
        this.dockSearchHotWords = dockSearchHotWords;
        this.reserved = reserved;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        DockSearchHotWordGroup t = (DockSearchHotWordGroup) o;
        return (
            com.qq.taf.jce.JceUtil.equals(groupName, t.groupName) && 
            com.qq.taf.jce.JceUtil.equals(dockSearchHotWords, t.dockSearchHotWords) && 
            com.qq.taf.jce.JceUtil.equals(reserved, t.reserved) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(groupName, 0);
        _os.write(dockSearchHotWords, 1);
        if (null != reserved)
        {
            _os.write(reserved, 2);
        }
    }

    static java.util.ArrayList<com.qq.jce.ws.DockSearchHotWord> cache_dockSearchHotWords;

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.groupName =  _is.readString(0, true);
        if(null == cache_dockSearchHotWords)
        {
            cache_dockSearchHotWords = new java.util.ArrayList<com.qq.jce.ws.DockSearchHotWord>();
            com.qq.jce.ws.DockSearchHotWord __var_7 = new com.qq.jce.ws.DockSearchHotWord();
            ((java.util.ArrayList<com.qq.jce.ws.DockSearchHotWord>)cache_dockSearchHotWords).add(__var_7);
        }
        this.dockSearchHotWords = (java.util.ArrayList<com.qq.jce.ws.DockSearchHotWord>) _is.read(cache_dockSearchHotWords, 1, true);
        this.reserved =  _is.readString(2, false);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(groupName, "groupName");
        _ds.display(dockSearchHotWords, "dockSearchHotWords");
        _ds.display(reserved, "reserved");
    }

    public void displaySimple(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.displaySimple(groupName, true);
        _ds.displaySimple(dockSearchHotWords, true);
        _ds.displaySimple(reserved, false);
    }

}

