// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/noahyang/ws.jce'
// **********************************************************************

package com.qq.jce.ws;

public final class DockRecommands extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "ws.DockRecommands";
    }

    public String fullClassName()
    {
        return "com.qq.jce.ws.DockRecommands";
    }

    public String title = "";

    public java.util.ArrayList<com.qq.jce.ws.DockRecommand> dockRecommandList = null;

    public String reserved = "";

    public String getTitle()
    {
        return title;
    }

    public void  setTitle(String title)
    {
        this.title = title;
    }

    public java.util.ArrayList<com.qq.jce.ws.DockRecommand> getDockRecommandList()
    {
        return dockRecommandList;
    }

    public void  setDockRecommandList(java.util.ArrayList<com.qq.jce.ws.DockRecommand> dockRecommandList)
    {
        this.dockRecommandList = dockRecommandList;
    }

    public String getReserved()
    {
        return reserved;
    }

    public void  setReserved(String reserved)
    {
        this.reserved = reserved;
    }

    public DockRecommands()
    {
    }

    public DockRecommands(String title, java.util.ArrayList<com.qq.jce.ws.DockRecommand> dockRecommandList, String reserved)
    {
        this.title = title;
        this.dockRecommandList = dockRecommandList;
        this.reserved = reserved;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        DockRecommands t = (DockRecommands) o;
        return (
            com.qq.taf.jce.JceUtil.equals(title, t.title) && 
            com.qq.taf.jce.JceUtil.equals(dockRecommandList, t.dockRecommandList) && 
            com.qq.taf.jce.JceUtil.equals(reserved, t.reserved) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(title, 0);
        _os.write(dockRecommandList, 1);
        if (null != reserved)
        {
            _os.write(reserved, 2);
        }
    }

    static java.util.ArrayList<com.qq.jce.ws.DockRecommand> cache_dockRecommandList;

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.title =  _is.readString(0, true);
        if(null == cache_dockRecommandList)
        {
            cache_dockRecommandList = new java.util.ArrayList<com.qq.jce.ws.DockRecommand>();
            com.qq.jce.ws.DockRecommand __var_9 = new com.qq.jce.ws.DockRecommand();
            ((java.util.ArrayList<com.qq.jce.ws.DockRecommand>)cache_dockRecommandList).add(__var_9);
        }
        this.dockRecommandList = (java.util.ArrayList<com.qq.jce.ws.DockRecommand>) _is.read(cache_dockRecommandList, 1, true);
        this.reserved =  _is.readString(2, false);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(title, "title");
        _ds.display(dockRecommandList, "dockRecommandList");
        _ds.display(reserved, "reserved");
    }

    public void displaySimple(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.displaySimple(title, true);
        _ds.displaySimple(dockRecommandList, true);
        _ds.displaySimple(reserved, false);
    }

}

