// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/noahyang/ws.jce'
// **********************************************************************

package com.qq.jce.ws;

public final class GetAppRecommandReq extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "ws.GetAppRecommandReq";
    }

    public String fullClassName()
    {
        return "com.qq.jce.ws.GetAppRecommandReq";
    }

    public String imei = "";

    public String uin = "";

    public String skey = "";

    public String getImei()
    {
        return imei;
    }

    public void  setImei(String imei)
    {
        this.imei = imei;
    }

    public String getUin()
    {
        return uin;
    }

    public void  setUin(String uin)
    {
        this.uin = uin;
    }

    public String getSkey()
    {
        return skey;
    }

    public void  setSkey(String skey)
    {
        this.skey = skey;
    }

    public GetAppRecommandReq()
    {
    }

    public GetAppRecommandReq(String imei, String uin, String skey)
    {
        this.imei = imei;
        this.uin = uin;
        this.skey = skey;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        GetAppRecommandReq t = (GetAppRecommandReq) o;
        return (
            com.qq.taf.jce.JceUtil.equals(imei, t.imei) && 
            com.qq.taf.jce.JceUtil.equals(uin, t.uin) && 
            com.qq.taf.jce.JceUtil.equals(skey, t.skey) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(imei, 0);
        if (null != uin)
        {
            _os.write(uin, 1);
        }
        if (null != skey)
        {
            _os.write(skey, 2);
        }
    }


    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.imei =  _is.readString(0, true);
        this.uin =  _is.readString(1, false);
        this.skey =  _is.readString(2, false);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(imei, "imei");
        _ds.display(uin, "uin");
        _ds.display(skey, "skey");
    }

    public void displaySimple(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.displaySimple(imei, true);
        _ds.displaySimple(uin, true);
        _ds.displaySimple(skey, false);
    }

}

