// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/noahyang/ws.jce'
// **********************************************************************

package com.qq.jce.ws;

public final class MAccessResponse extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "ws.MAccessResponse";
    }

    public String fullClassName()
    {
        return "com.qq.jce.ws.MAccessResponse";
    }

    public com.qq.jce.ws.MAccessRspHead mAccessRspHead = null;

    public byte [] body = null;

    public com.qq.jce.ws.MAccessRspHead getMAccessRspHead()
    {
        return mAccessRspHead;
    }

    public void  setMAccessRspHead(com.qq.jce.ws.MAccessRspHead mAccessRspHead)
    {
        this.mAccessRspHead = mAccessRspHead;
    }

    public byte [] getBody()
    {
        return body;
    }

    public void  setBody(byte [] body)
    {
        this.body = body;
    }

    public MAccessResponse()
    {
    }

    public MAccessResponse(com.qq.jce.ws.MAccessRspHead mAccessRspHead, byte [] body)
    {
        this.mAccessRspHead = mAccessRspHead;
        this.body = body;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        MAccessResponse t = (MAccessResponse) o;
        return (
            com.qq.taf.jce.JceUtil.equals(mAccessRspHead, t.mAccessRspHead) && 
            com.qq.taf.jce.JceUtil.equals(body, t.body) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(mAccessRspHead, 0);
        _os.write(body, 1);
    }

    static com.qq.jce.ws.MAccessRspHead cache_mAccessRspHead;
    static byte [] cache_body;

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        if(null == cache_mAccessRspHead)
        {
            cache_mAccessRspHead = new com.qq.jce.ws.MAccessRspHead();
        }
        this.mAccessRspHead = (com.qq.jce.ws.MAccessRspHead) _is.read(cache_mAccessRspHead, 0, true);
        if(null == cache_body)
        {
            cache_body = (byte[]) new byte[1];
            byte __var_13 = 0;
            ((byte[])cache_body)[0] = __var_13;
        }
        this.body = (byte []) _is.read(cache_body, 1, true);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(mAccessRspHead, "mAccessRspHead");
        _ds.display(body, "body");
    }

    public void displaySimple(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.displaySimple(mAccessRspHead, true);
        _ds.displaySimple(body, false);
    }

}

