// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/noahyang/wmarket.jce'
// **********************************************************************

package com.qq.jce.vmarket.wmarket;

public final class AppGroup extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "wmarket.AppGroup";
    }

    public String fullClassName()
    {
        return "com.qq.jce.vmarket.wmarket.AppGroup";
    }

    public int columnId = 0;

    public String name = "";

    public String desc = "";

    public String iconUrl = "";

    public java.util.ArrayList<String> pkgNameList = null;

    public int type = 0;

    public int getColumnId()
    {
        return columnId;
    }

    public void  setColumnId(int columnId)
    {
        this.columnId = columnId;
    }

    public String getName()
    {
        return name;
    }

    public void  setName(String name)
    {
        this.name = name;
    }

    public String getDesc()
    {
        return desc;
    }

    public void  setDesc(String desc)
    {
        this.desc = desc;
    }

    public String getIconUrl()
    {
        return iconUrl;
    }

    public void  setIconUrl(String iconUrl)
    {
        this.iconUrl = iconUrl;
    }

    public java.util.ArrayList<String> getPkgNameList()
    {
        return pkgNameList;
    }

    public void  setPkgNameList(java.util.ArrayList<String> pkgNameList)
    {
        this.pkgNameList = pkgNameList;
    }

    public int getType()
    {
        return type;
    }

    public void  setType(int type)
    {
        this.type = type;
    }

    public AppGroup()
    {
    }

    public AppGroup(int columnId, String name, String desc, String iconUrl, java.util.ArrayList<String> pkgNameList, int type)
    {
        this.columnId = columnId;
        this.name = name;
        this.desc = desc;
        this.iconUrl = iconUrl;
        this.pkgNameList = pkgNameList;
        this.type = type;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        AppGroup t = (AppGroup) o;
        return (
            com.qq.taf.jce.JceUtil.equals(columnId, t.columnId) && 
            com.qq.taf.jce.JceUtil.equals(name, t.name) && 
            com.qq.taf.jce.JceUtil.equals(desc, t.desc) && 
            com.qq.taf.jce.JceUtil.equals(iconUrl, t.iconUrl) && 
            com.qq.taf.jce.JceUtil.equals(pkgNameList, t.pkgNameList) && 
            com.qq.taf.jce.JceUtil.equals(type, t.type) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(columnId, 0);
        _os.write(name, 1);
        if (null != desc)
        {
            _os.write(desc, 2);
        }
        if (null != iconUrl)
        {
            _os.write(iconUrl, 3);
        }
        if (null != pkgNameList)
        {
            _os.write(pkgNameList, 4);
        }
        _os.write(type, 5);
    }

    static java.util.ArrayList<String> cache_pkgNameList;

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.columnId = (int) _is.read(columnId, 0, true);
        this.name =  _is.readString(1, true);
        this.desc =  _is.readString(2, false);
        this.iconUrl =  _is.readString(3, false);
        if(null == cache_pkgNameList)
        {
            cache_pkgNameList = new java.util.ArrayList<String>();
            String __var_37 = "";
            ((java.util.ArrayList<String>)cache_pkgNameList).add(__var_37);
        }
        this.pkgNameList = (java.util.ArrayList<String>) _is.read(cache_pkgNameList, 4, false);
        this.type = (int) _is.read(type, 5, false);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(columnId, "columnId");
        _ds.display(name, "name");
        _ds.display(desc, "desc");
        _ds.display(iconUrl, "iconUrl");
        _ds.display(pkgNameList, "pkgNameList");
        _ds.display(type, "type");
    }

    public void displaySimple(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.displaySimple(columnId, true);
        _ds.displaySimple(name, true);
        _ds.displaySimple(desc, true);
        _ds.displaySimple(iconUrl, true);
        _ds.displaySimple(pkgNameList, true);
        _ds.displaySimple(type, false);
    }

}

