// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/noahyang/wmarket.jce'
// **********************************************************************

package com.qq.jce.vmarket.wmarket;

public final class AppInfoForUpdate extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "wmarket.AppInfoForUpdate";
    }

    public String fullClassName()
    {
        return "com.qq.jce.vmarket.wmarket.AppInfoForUpdate";
    }

    public String packageName = "";

    public int versionCode = 0;

    public String manifestMd5 = "";

    public byte appType = 1;

    public String versionName = "";

    public String signatureMd5 = "";

    public String signatureMd5Molo = "";

    public String getPackageName()
    {
        return packageName;
    }

    public void  setPackageName(String packageName)
    {
        this.packageName = packageName;
    }

    public int getVersionCode()
    {
        return versionCode;
    }

    public void  setVersionCode(int versionCode)
    {
        this.versionCode = versionCode;
    }

    public String getManifestMd5()
    {
        return manifestMd5;
    }

    public void  setManifestMd5(String manifestMd5)
    {
        this.manifestMd5 = manifestMd5;
    }

    public byte getAppType()
    {
        return appType;
    }

    public void  setAppType(byte appType)
    {
        this.appType = appType;
    }

    public String getVersionName()
    {
        return versionName;
    }

    public void  setVersionName(String versionName)
    {
        this.versionName = versionName;
    }

    public String getSignatureMd5()
    {
        return signatureMd5;
    }

    public void  setSignatureMd5(String signatureMd5)
    {
        this.signatureMd5 = signatureMd5;
    }

    public String getSignatureMd5Molo()
    {
        return signatureMd5Molo;
    }

    public void  setSignatureMd5Molo(String signatureMd5Molo)
    {
        this.signatureMd5Molo = signatureMd5Molo;
    }

    public AppInfoForUpdate()
    {
    }

    public AppInfoForUpdate(String packageName, int versionCode, String manifestMd5, byte appType, String versionName, String signatureMd5, String signatureMd5Molo)
    {
        this.packageName = packageName;
        this.versionCode = versionCode;
        this.manifestMd5 = manifestMd5;
        this.appType = appType;
        this.versionName = versionName;
        this.signatureMd5 = signatureMd5;
        this.signatureMd5Molo = signatureMd5Molo;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        AppInfoForUpdate t = (AppInfoForUpdate) o;
        return (
            com.qq.taf.jce.JceUtil.equals(packageName, t.packageName) && 
            com.qq.taf.jce.JceUtil.equals(versionCode, t.versionCode) && 
            com.qq.taf.jce.JceUtil.equals(manifestMd5, t.manifestMd5) && 
            com.qq.taf.jce.JceUtil.equals(appType, t.appType) && 
            com.qq.taf.jce.JceUtil.equals(versionName, t.versionName) && 
            com.qq.taf.jce.JceUtil.equals(signatureMd5, t.signatureMd5) && 
            com.qq.taf.jce.JceUtil.equals(signatureMd5Molo, t.signatureMd5Molo) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(packageName, 0);
        _os.write(versionCode, 1);
        _os.write(manifestMd5, 2);
        _os.write(appType, 3);
        if (null != versionName)
        {
            _os.write(versionName, 4);
        }
        if (null != signatureMd5)
        {
            _os.write(signatureMd5, 5);
        }
        if (null != signatureMd5Molo)
        {
            _os.write(signatureMd5Molo, 6);
        }
    }


    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.packageName =  _is.readString(0, true);
        this.versionCode = (int) _is.read(versionCode, 1, true);
        this.manifestMd5 =  _is.readString(2, true);
        this.appType = (byte) _is.read(appType, 3, false);
        this.versionName =  _is.readString(4, false);
        this.signatureMd5 =  _is.readString(5, false);
        this.signatureMd5Molo =  _is.readString(6, false);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(packageName, "packageName");
        _ds.display(versionCode, "versionCode");
        _ds.display(manifestMd5, "manifestMd5");
        _ds.display(appType, "appType");
        _ds.display(versionName, "versionName");
        _ds.display(signatureMd5, "signatureMd5");
        _ds.display(signatureMd5Molo, "signatureMd5Molo");
    }

    public void displaySimple(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.displaySimple(packageName, true);
        _ds.displaySimple(versionCode, true);
        _ds.displaySimple(manifestMd5, true);
        _ds.displaySimple(appType, true);
        _ds.displaySimple(versionName, true);
        _ds.displaySimple(signatureMd5, true);
        _ds.displaySimple(signatureMd5Molo, false);
    }

}

