// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/noahyang/wmarket.jce'
// **********************************************************************

package com.qq.jce.vmarket.wmarket;

public final class Banner extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "wmarket.Banner";
    }

    public String fullClassName()
    {
        return "com.qq.jce.vmarket.wmarket.Banner";
    }

    public String toUrl = "";

    public String picUrl = "";

    public String title = "";

    public String content = "";

    public int type = 0;

    public int ziprate = 0;

    public String picUrl_m = "";

    public String picUrl_s = "";

    public String getToUrl()
    {
        return toUrl;
    }

    public void  setToUrl(String toUrl)
    {
        this.toUrl = toUrl;
    }

    public String getPicUrl()
    {
        return picUrl;
    }

    public void  setPicUrl(String picUrl)
    {
        this.picUrl = picUrl;
    }

    public String getTitle()
    {
        return title;
    }

    public void  setTitle(String title)
    {
        this.title = title;
    }

    public String getContent()
    {
        return content;
    }

    public void  setContent(String content)
    {
        this.content = content;
    }

    public int getType()
    {
        return type;
    }

    public void  setType(int type)
    {
        this.type = type;
    }

    public int getZiprate()
    {
        return ziprate;
    }

    public void  setZiprate(int ziprate)
    {
        this.ziprate = ziprate;
    }

    public String getPicUrl_m()
    {
        return picUrl_m;
    }

    public void  setPicUrl_m(String picUrl_m)
    {
        this.picUrl_m = picUrl_m;
    }

    public String getPicUrl_s()
    {
        return picUrl_s;
    }

    public void  setPicUrl_s(String picUrl_s)
    {
        this.picUrl_s = picUrl_s;
    }

    public Banner()
    {
    }

    public Banner(String toUrl, String picUrl, String title, String content, int type, int ziprate, String picUrl_m, String picUrl_s)
    {
        this.toUrl = toUrl;
        this.picUrl = picUrl;
        this.title = title;
        this.content = content;
        this.type = type;
        this.ziprate = ziprate;
        this.picUrl_m = picUrl_m;
        this.picUrl_s = picUrl_s;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        Banner t = (Banner) o;
        return (
            com.qq.taf.jce.JceUtil.equals(toUrl, t.toUrl) && 
            com.qq.taf.jce.JceUtil.equals(picUrl, t.picUrl) && 
            com.qq.taf.jce.JceUtil.equals(title, t.title) && 
            com.qq.taf.jce.JceUtil.equals(content, t.content) && 
            com.qq.taf.jce.JceUtil.equals(type, t.type) && 
            com.qq.taf.jce.JceUtil.equals(ziprate, t.ziprate) && 
            com.qq.taf.jce.JceUtil.equals(picUrl_m, t.picUrl_m) && 
            com.qq.taf.jce.JceUtil.equals(picUrl_s, t.picUrl_s) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(toUrl, 0);
        _os.write(picUrl, 1);
        _os.write(title, 2);
        if (null != content)
        {
            _os.write(content, 3);
        }
        _os.write(type, 4);
        _os.write(ziprate, 5);
        if (null != picUrl_m)
        {
            _os.write(picUrl_m, 6);
        }
        if (null != picUrl_s)
        {
            _os.write(picUrl_s, 7);
        }
    }


    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.toUrl =  _is.readString(0, true);
        this.picUrl =  _is.readString(1, true);
        this.title =  _is.readString(2, true);
        this.content =  _is.readString(3, false);
        this.type = (int) _is.read(type, 4, false);
        this.ziprate = (int) _is.read(ziprate, 5, false);
        this.picUrl_m =  _is.readString(6, false);
        this.picUrl_s =  _is.readString(7, false);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(toUrl, "toUrl");
        _ds.display(picUrl, "picUrl");
        _ds.display(title, "title");
        _ds.display(content, "content");
        _ds.display(type, "type");
        _ds.display(ziprate, "ziprate");
        _ds.display(picUrl_m, "picUrl_m");
        _ds.display(picUrl_s, "picUrl_s");
    }

    public void displaySimple(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.displaySimple(toUrl, true);
        _ds.displaySimple(picUrl, true);
        _ds.displaySimple(title, true);
        _ds.displaySimple(content, true);
        _ds.displaySimple(type, true);
        _ds.displaySimple(ziprate, true);
        _ds.displaySimple(picUrl_m, true);
        _ds.displaySimple(picUrl_s, false);
    }

}

