// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/noahyang/wmarket.jce'
// **********************************************************************

package com.qq.jce.vmarket.wmarket;

public final class GetAppListRsp extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "wmarket.GetAppListRsp";
    }

    public String fullClassName()
    {
        return "com.qq.jce.vmarket.wmarket.GetAppListRsp";
    }

    public int ret = 0;

    public java.util.ArrayList<com.qq.jce.vmarket.wmarket.AppDetail> appList = null;

    public byte [] contextData = null;

    public int hasNext = 0;

    public int getRet()
    {
        return ret;
    }

    public void  setRet(int ret)
    {
        this.ret = ret;
    }

    public java.util.ArrayList<com.qq.jce.vmarket.wmarket.AppDetail> getAppList()
    {
        return appList;
    }

    public void  setAppList(java.util.ArrayList<com.qq.jce.vmarket.wmarket.AppDetail> appList)
    {
        this.appList = appList;
    }

    public byte [] getContextData()
    {
        return contextData;
    }

    public void  setContextData(byte [] contextData)
    {
        this.contextData = contextData;
    }

    public int getHasNext()
    {
        return hasNext;
    }

    public void  setHasNext(int hasNext)
    {
        this.hasNext = hasNext;
    }

    public GetAppListRsp()
    {
    }

    public GetAppListRsp(int ret, java.util.ArrayList<com.qq.jce.vmarket.wmarket.AppDetail> appList, byte [] contextData, int hasNext)
    {
        this.ret = ret;
        this.appList = appList;
        this.contextData = contextData;
        this.hasNext = hasNext;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        GetAppListRsp t = (GetAppListRsp) o;
        return (
            com.qq.taf.jce.JceUtil.equals(ret, t.ret) && 
            com.qq.taf.jce.JceUtil.equals(appList, t.appList) && 
            com.qq.taf.jce.JceUtil.equals(contextData, t.contextData) && 
            com.qq.taf.jce.JceUtil.equals(hasNext, t.hasNext) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(ret, 0);
        _os.write(appList, 1);
        if (null != contextData)
        {
            _os.write(contextData, 2);
        }
        _os.write(hasNext, 3);
    }

    static java.util.ArrayList<com.qq.jce.vmarket.wmarket.AppDetail> cache_appList;
    static byte [] cache_contextData;

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.ret = (int) _is.read(ret, 0, true);
        if(null == cache_appList)
        {
            cache_appList = new java.util.ArrayList<com.qq.jce.vmarket.wmarket.AppDetail>();
            com.qq.jce.vmarket.wmarket.AppDetail __var_8 = new com.qq.jce.vmarket.wmarket.AppDetail();
            ((java.util.ArrayList<com.qq.jce.vmarket.wmarket.AppDetail>)cache_appList).add(__var_8);
        }
        this.appList = (java.util.ArrayList<com.qq.jce.vmarket.wmarket.AppDetail>) _is.read(cache_appList, 1, true);
        if(null == cache_contextData)
        {
            cache_contextData = (byte[]) new byte[1];
            byte __var_9 = 0;
            ((byte[])cache_contextData)[0] = __var_9;
        }
        this.contextData = (byte []) _is.read(cache_contextData, 2, false);
        this.hasNext = (int) _is.read(hasNext, 3, false);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(ret, "ret");
        _ds.display(appList, "appList");
        _ds.display(contextData, "contextData");
        _ds.display(hasNext, "hasNext");
    }

    public void displaySimple(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.displaySimple(ret, true);
        _ds.displaySimple(appList, true);
        _ds.displaySimple(contextData, true);
        _ds.displaySimple(hasNext, false);
    }

}

