// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/noahyang/wmarket.jce'
// **********************************************************************

package com.qq.jce.vmarket.wmarket;

public final class GetBannerReq extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "wmarket.GetBannerReq";
    }

    public String fullClassName()
    {
        return "com.qq.jce.vmarket.wmarket.GetBannerReq";
    }

    public java.util.ArrayList<Integer> types = null;

    public java.util.ArrayList<Integer> getTypes()
    {
        return types;
    }

    public void  setTypes(java.util.ArrayList<Integer> types)
    {
        this.types = types;
    }

    public GetBannerReq()
    {
    }

    public GetBannerReq(java.util.ArrayList<Integer> types)
    {
        this.types = types;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        GetBannerReq t = (GetBannerReq) o;
        return (
            com.qq.taf.jce.JceUtil.equals(types, t.types) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(types, 0);
    }

    static java.util.ArrayList<Integer> cache_types;

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        if(null == cache_types)
        {
            cache_types = new java.util.ArrayList<Integer>();
            Integer __var_10 = 0;
            ((java.util.ArrayList<Integer>)cache_types).add(__var_10);
        }
        this.types = (java.util.ArrayList<Integer>) _is.read(cache_types, 0, true);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(types, "types");
    }

    public void displaySimple(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.displaySimple(types, false);
    }

}

