// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/noahyang/wmarket.jce'
// **********************************************************************

package com.qq.jce.vmarket.wmarket;

public final class GetBannerRsp extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "wmarket.GetBannerRsp";
    }

    public String fullClassName()
    {
        return "com.qq.jce.vmarket.wmarket.GetBannerRsp";
    }

    public java.util.ArrayList<com.qq.jce.vmarket.wmarket.Banner> bannerList = null;

    public java.util.ArrayList<com.qq.jce.vmarket.wmarket.Banner> getBannerList()
    {
        return bannerList;
    }

    public void  setBannerList(java.util.ArrayList<com.qq.jce.vmarket.wmarket.Banner> bannerList)
    {
        this.bannerList = bannerList;
    }

    public GetBannerRsp()
    {
    }

    public GetBannerRsp(java.util.ArrayList<com.qq.jce.vmarket.wmarket.Banner> bannerList)
    {
        this.bannerList = bannerList;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        GetBannerRsp t = (GetBannerRsp) o;
        return (
            com.qq.taf.jce.JceUtil.equals(bannerList, t.bannerList) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(bannerList, 0);
    }

    static java.util.ArrayList<com.qq.jce.vmarket.wmarket.Banner> cache_bannerList;

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        if(null == cache_bannerList)
        {
            cache_bannerList = new java.util.ArrayList<com.qq.jce.vmarket.wmarket.Banner>();
            com.qq.jce.vmarket.wmarket.Banner __var_11 = new com.qq.jce.vmarket.wmarket.Banner();
            ((java.util.ArrayList<com.qq.jce.vmarket.wmarket.Banner>)cache_bannerList).add(__var_11);
        }
        this.bannerList = (java.util.ArrayList<com.qq.jce.vmarket.wmarket.Banner>) _is.read(cache_bannerList, 0, true);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(bannerList, "bannerList");
    }

    public void displaySimple(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.displaySimple(bannerList, false);
    }

}

