// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/noahyang/wmarket.jce'
// **********************************************************************

package com.qq.jce.vmarket.wmarket;

public final class GetCategoryListRsp extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "wmarket.GetCategoryListRsp";
    }

    public String fullClassName()
    {
        return "com.qq.jce.vmarket.wmarket.GetCategoryListRsp";
    }

    public int ret = 0;

    public java.util.ArrayList<com.qq.jce.vmarket.wmarket.CategoryDetail> categoryList = null;

    public int getRet()
    {
        return ret;
    }

    public void  setRet(int ret)
    {
        this.ret = ret;
    }

    public java.util.ArrayList<com.qq.jce.vmarket.wmarket.CategoryDetail> getCategoryList()
    {
        return categoryList;
    }

    public void  setCategoryList(java.util.ArrayList<com.qq.jce.vmarket.wmarket.CategoryDetail> categoryList)
    {
        this.categoryList = categoryList;
    }

    public GetCategoryListRsp()
    {
    }

    public GetCategoryListRsp(int ret, java.util.ArrayList<com.qq.jce.vmarket.wmarket.CategoryDetail> categoryList)
    {
        this.ret = ret;
        this.categoryList = categoryList;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        GetCategoryListRsp t = (GetCategoryListRsp) o;
        return (
            com.qq.taf.jce.JceUtil.equals(ret, t.ret) && 
            com.qq.taf.jce.JceUtil.equals(categoryList, t.categoryList) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(ret, 0);
        _os.write(categoryList, 1);
    }

    static java.util.ArrayList<com.qq.jce.vmarket.wmarket.CategoryDetail> cache_categoryList;

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.ret = (int) _is.read(ret, 0, true);
        if(null == cache_categoryList)
        {
            cache_categoryList = new java.util.ArrayList<com.qq.jce.vmarket.wmarket.CategoryDetail>();
            com.qq.jce.vmarket.wmarket.CategoryDetail __var_15 = new com.qq.jce.vmarket.wmarket.CategoryDetail();
            ((java.util.ArrayList<com.qq.jce.vmarket.wmarket.CategoryDetail>)cache_categoryList).add(__var_15);
        }
        this.categoryList = (java.util.ArrayList<com.qq.jce.vmarket.wmarket.CategoryDetail>) _is.read(cache_categoryList, 1, true);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(ret, "ret");
        _ds.display(categoryList, "categoryList");
    }

    public void displaySimple(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.displaySimple(ret, true);
        _ds.displaySimple(categoryList, false);
    }

}

