// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/noahyang/wmarket.jce'
// **********************************************************************

package com.qq.jce.vmarket.wmarket;

public final class GetChickenEssenceReq extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "wmarket.GetChickenEssenceReq";
    }

    public String fullClassName()
    {
        return "com.qq.jce.vmarket.wmarket.GetChickenEssenceReq";
    }

    public int type = 0;

    public int getType()
    {
        return type;
    }

    public void  setType(int type)
    {
        this.type = type;
    }

    public GetChickenEssenceReq()
    {
    }

    public GetChickenEssenceReq(int type)
    {
        this.type = type;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        GetChickenEssenceReq t = (GetChickenEssenceReq) o;
        return (
            com.qq.taf.jce.JceUtil.equals(type, t.type) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(type, 0);
    }


    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.type = (int) _is.read(type, 0, true);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(type, "type");
    }

    public void displaySimple(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.displaySimple(type, false);
    }

}

