// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/noahyang/wmarket.jce'
// **********************************************************************

package com.qq.jce.vmarket.wmarket;

public final class GetIndexUnionsRsp extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "wmarket.GetIndexUnionsRsp";
    }

    public String fullClassName()
    {
        return "com.qq.jce.vmarket.wmarket.GetIndexUnionsRsp";
    }

    public int ret = 0;

    public String msg = "";

    public java.util.ArrayList<com.qq.jce.vmarket.wmarket.Union> unions = null;

    public int getRet()
    {
        return ret;
    }

    public void  setRet(int ret)
    {
        this.ret = ret;
    }

    public String getMsg()
    {
        return msg;
    }

    public void  setMsg(String msg)
    {
        this.msg = msg;
    }

    public java.util.ArrayList<com.qq.jce.vmarket.wmarket.Union> getUnions()
    {
        return unions;
    }

    public void  setUnions(java.util.ArrayList<com.qq.jce.vmarket.wmarket.Union> unions)
    {
        this.unions = unions;
    }

    public GetIndexUnionsRsp()
    {
    }

    public GetIndexUnionsRsp(int ret, String msg, java.util.ArrayList<com.qq.jce.vmarket.wmarket.Union> unions)
    {
        this.ret = ret;
        this.msg = msg;
        this.unions = unions;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        GetIndexUnionsRsp t = (GetIndexUnionsRsp) o;
        return (
            com.qq.taf.jce.JceUtil.equals(ret, t.ret) && 
            com.qq.taf.jce.JceUtil.equals(msg, t.msg) && 
            com.qq.taf.jce.JceUtil.equals(unions, t.unions) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(ret, 0);
        if (null != msg)
        {
            _os.write(msg, 1);
        }
        if (null != unions)
        {
            _os.write(unions, 2);
        }
    }

    static java.util.ArrayList<com.qq.jce.vmarket.wmarket.Union> cache_unions;

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.ret = (int) _is.read(ret, 0, true);
        this.msg =  _is.readString(1, false);
        if(null == cache_unions)
        {
            cache_unions = new java.util.ArrayList<com.qq.jce.vmarket.wmarket.Union>();
            com.qq.jce.vmarket.wmarket.Union __var_25 = new com.qq.jce.vmarket.wmarket.Union();
            ((java.util.ArrayList<com.qq.jce.vmarket.wmarket.Union>)cache_unions).add(__var_25);
        }
        this.unions = (java.util.ArrayList<com.qq.jce.vmarket.wmarket.Union>) _is.read(cache_unions, 2, false);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(ret, "ret");
        _ds.display(msg, "msg");
        _ds.display(unions, "unions");
    }

    public void displaySimple(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.displaySimple(ret, true);
        _ds.displaySimple(msg, true);
        _ds.displaySimple(unions, false);
    }

}

