// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/noahyang/wmarket.jce'
// **********************************************************************

package com.qq.jce.vmarket.wmarket;

public final class GetOpcRankListRsp extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "wmarket.GetOpcRankListRsp";
    }

    public String fullClassName()
    {
        return "com.qq.jce.vmarket.wmarket.GetOpcRankListRsp";
    }

    public java.util.ArrayList<com.qq.jce.vmarket.wmarket.OpcRank> opcRankList = null;

    public java.util.ArrayList<com.qq.jce.vmarket.wmarket.OpcRank> getOpcRankList()
    {
        return opcRankList;
    }

    public void  setOpcRankList(java.util.ArrayList<com.qq.jce.vmarket.wmarket.OpcRank> opcRankList)
    {
        this.opcRankList = opcRankList;
    }

    public GetOpcRankListRsp()
    {
    }

    public GetOpcRankListRsp(java.util.ArrayList<com.qq.jce.vmarket.wmarket.OpcRank> opcRankList)
    {
        this.opcRankList = opcRankList;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        GetOpcRankListRsp t = (GetOpcRankListRsp) o;
        return (
            com.qq.taf.jce.JceUtil.equals(opcRankList, t.opcRankList) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(opcRankList, 0);
    }

    static java.util.ArrayList<com.qq.jce.vmarket.wmarket.OpcRank> cache_opcRankList;

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        if(null == cache_opcRankList)
        {
            cache_opcRankList = new java.util.ArrayList<com.qq.jce.vmarket.wmarket.OpcRank>();
            com.qq.jce.vmarket.wmarket.OpcRank __var_43 = new com.qq.jce.vmarket.wmarket.OpcRank();
            ((java.util.ArrayList<com.qq.jce.vmarket.wmarket.OpcRank>)cache_opcRankList).add(__var_43);
        }
        this.opcRankList = (java.util.ArrayList<com.qq.jce.vmarket.wmarket.OpcRank>) _is.read(cache_opcRankList, 0, true);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(opcRankList, "opcRankList");
    }

    public void displaySimple(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.displaySimple(opcRankList, false);
    }

}

