// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/noahyang/wmarket.jce'
// **********************************************************************

package com.qq.jce.vmarket.wmarket;

public final class GetOpcRankListReqHolder
{
    public GetOpcRankListReqHolder()
    {
    }
    public GetOpcRankListReqHolder(GetOpcRankListReq value)
    {
        this.value = value;
    }

    public GetOpcRankListReq value;
}
