// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/noahyang/wmarket.jce'
// **********************************************************************

package com.qq.jce.vmarket.wmarket;

public final class SearchAppReq extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "wmarket.SearchAppReq";
    }

    public String fullClassName()
    {
        return "com.qq.jce.vmarket.wmarket.SearchAppReq";
    }

    public String keyword = "";

    public byte [] contextData = null;

    public int pageSize = 0;

    public int searchScene = 0;

    public long searchId = 0;

    public String getKeyword()
    {
        return keyword;
    }

    public void  setKeyword(String keyword)
    {
        this.keyword = keyword;
    }

    public byte [] getContextData()
    {
        return contextData;
    }

    public void  setContextData(byte [] contextData)
    {
        this.contextData = contextData;
    }

    public int getPageSize()
    {
        return pageSize;
    }

    public void  setPageSize(int pageSize)
    {
        this.pageSize = pageSize;
    }

    public int getSearchScene()
    {
        return searchScene;
    }

    public void  setSearchScene(int searchScene)
    {
        this.searchScene = searchScene;
    }

    public long getSearchId()
    {
        return searchId;
    }

    public void  setSearchId(long searchId)
    {
        this.searchId = searchId;
    }

    public SearchAppReq()
    {
    }

    public SearchAppReq(String keyword, byte [] contextData, int pageSize, int searchScene, long searchId)
    {
        this.keyword = keyword;
        this.contextData = contextData;
        this.pageSize = pageSize;
        this.searchScene = searchScene;
        this.searchId = searchId;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        SearchAppReq t = (SearchAppReq) o;
        return (
            com.qq.taf.jce.JceUtil.equals(keyword, t.keyword) && 
            com.qq.taf.jce.JceUtil.equals(contextData, t.contextData) && 
            com.qq.taf.jce.JceUtil.equals(pageSize, t.pageSize) && 
            com.qq.taf.jce.JceUtil.equals(searchScene, t.searchScene) && 
            com.qq.taf.jce.JceUtil.equals(searchId, t.searchId) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(keyword, 0);
        if (null != contextData)
        {
            _os.write(contextData, 1);
        }
        _os.write(pageSize, 2);
        _os.write(searchScene, 3);
        _os.write(searchId, 4);
    }

    static byte [] cache_contextData;

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.keyword =  _is.readString(0, true);
        if(null == cache_contextData)
        {
            cache_contextData = (byte[]) new byte[1];
            byte __var_32 = 0;
            ((byte[])cache_contextData)[0] = __var_32;
        }
        this.contextData = (byte []) _is.read(cache_contextData, 1, false);
        this.pageSize = (int) _is.read(pageSize, 2, false);
        this.searchScene = (int) _is.read(searchScene, 3, false);
        this.searchId = (long) _is.read(searchId, 4, false);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(keyword, "keyword");
        _ds.display(contextData, "contextData");
        _ds.display(pageSize, "pageSize");
        _ds.display(searchScene, "searchScene");
        _ds.display(searchId, "searchId");
    }

    public void displaySimple(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.displaySimple(keyword, true);
        _ds.displaySimple(contextData, true);
        _ds.displaySimple(pageSize, true);
        _ds.displaySimple(searchScene, true);
        _ds.displaySimple(searchId, false);
    }

}

