// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/noahyang/wmarket.jce'
// **********************************************************************

package com.qq.jce.vmarket.wmarket;

public final class SearchRspItem extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "wmarket.SearchRspItem";
    }

    public String fullClassName()
    {
        return "com.qq.jce.vmarket.wmarket.SearchRspItem";
    }

    public int type = 0;

    public String pkgName = "";

    public String downloadRateDesc = "";

    public java.util.ArrayList<String> pkgNameList = null;

    public String topDesc = "";

    public String bottomDesc = "";

    public com.qq.jce.vmarket.wmarket.AppDetail appDetail = null;

    public java.util.ArrayList<com.qq.jce.vmarket.wmarket.AppDetail> appList = null;

    public int getType()
    {
        return type;
    }

    public void  setType(int type)
    {
        this.type = type;
    }

    public String getPkgName()
    {
        return pkgName;
    }

    public void  setPkgName(String pkgName)
    {
        this.pkgName = pkgName;
    }

    public String getDownloadRateDesc()
    {
        return downloadRateDesc;
    }

    public void  setDownloadRateDesc(String downloadRateDesc)
    {
        this.downloadRateDesc = downloadRateDesc;
    }

    public java.util.ArrayList<String> getPkgNameList()
    {
        return pkgNameList;
    }

    public void  setPkgNameList(java.util.ArrayList<String> pkgNameList)
    {
        this.pkgNameList = pkgNameList;
    }

    public String getTopDesc()
    {
        return topDesc;
    }

    public void  setTopDesc(String topDesc)
    {
        this.topDesc = topDesc;
    }

    public String getBottomDesc()
    {
        return bottomDesc;
    }

    public void  setBottomDesc(String bottomDesc)
    {
        this.bottomDesc = bottomDesc;
    }

    public com.qq.jce.vmarket.wmarket.AppDetail getAppDetail()
    {
        return appDetail;
    }

    public void  setAppDetail(com.qq.jce.vmarket.wmarket.AppDetail appDetail)
    {
        this.appDetail = appDetail;
    }

    public java.util.ArrayList<com.qq.jce.vmarket.wmarket.AppDetail> getAppList()
    {
        return appList;
    }

    public void  setAppList(java.util.ArrayList<com.qq.jce.vmarket.wmarket.AppDetail> appList)
    {
        this.appList = appList;
    }

    public SearchRspItem()
    {
    }

    public SearchRspItem(int type, String pkgName, String downloadRateDesc, java.util.ArrayList<String> pkgNameList, String topDesc, String bottomDesc, com.qq.jce.vmarket.wmarket.AppDetail appDetail, java.util.ArrayList<com.qq.jce.vmarket.wmarket.AppDetail> appList)
    {
        this.type = type;
        this.pkgName = pkgName;
        this.downloadRateDesc = downloadRateDesc;
        this.pkgNameList = pkgNameList;
        this.topDesc = topDesc;
        this.bottomDesc = bottomDesc;
        this.appDetail = appDetail;
        this.appList = appList;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        SearchRspItem t = (SearchRspItem) o;
        return (
            com.qq.taf.jce.JceUtil.equals(type, t.type) && 
            com.qq.taf.jce.JceUtil.equals(pkgName, t.pkgName) && 
            com.qq.taf.jce.JceUtil.equals(downloadRateDesc, t.downloadRateDesc) && 
            com.qq.taf.jce.JceUtil.equals(pkgNameList, t.pkgNameList) && 
            com.qq.taf.jce.JceUtil.equals(topDesc, t.topDesc) && 
            com.qq.taf.jce.JceUtil.equals(bottomDesc, t.bottomDesc) && 
            com.qq.taf.jce.JceUtil.equals(appDetail, t.appDetail) && 
            com.qq.taf.jce.JceUtil.equals(appList, t.appList) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(type, 0);
        if (null != pkgName)
        {
            _os.write(pkgName, 1);
        }
        if (null != downloadRateDesc)
        {
            _os.write(downloadRateDesc, 2);
        }
        if (null != pkgNameList)
        {
            _os.write(pkgNameList, 3);
        }
        if (null != topDesc)
        {
            _os.write(topDesc, 4);
        }
        if (null != bottomDesc)
        {
            _os.write(bottomDesc, 5);
        }
        if (null != appDetail)
        {
            _os.write(appDetail, 6);
        }
        if (null != appList)
        {
            _os.write(appList, 7);
        }
    }

    static java.util.ArrayList<String> cache_pkgNameList;
    static com.qq.jce.vmarket.wmarket.AppDetail cache_appDetail;
    static java.util.ArrayList<com.qq.jce.vmarket.wmarket.AppDetail> cache_appList;

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.type = (int) _is.read(type, 0, true);
        this.pkgName =  _is.readString(1, false);
        this.downloadRateDesc =  _is.readString(2, false);
        if(null == cache_pkgNameList)
        {
            cache_pkgNameList = new java.util.ArrayList<String>();
            String __var_30 = "";
            ((java.util.ArrayList<String>)cache_pkgNameList).add(__var_30);
        }
        this.pkgNameList = (java.util.ArrayList<String>) _is.read(cache_pkgNameList, 3, false);
        this.topDesc =  _is.readString(4, false);
        this.bottomDesc =  _is.readString(5, false);
        if(null == cache_appDetail)
        {
            cache_appDetail = new com.qq.jce.vmarket.wmarket.AppDetail();
        }
        this.appDetail = (com.qq.jce.vmarket.wmarket.AppDetail) _is.read(cache_appDetail, 6, false);
        if(null == cache_appList)
        {
            cache_appList = new java.util.ArrayList<com.qq.jce.vmarket.wmarket.AppDetail>();
            com.qq.jce.vmarket.wmarket.AppDetail __var_31 = new com.qq.jce.vmarket.wmarket.AppDetail();
            ((java.util.ArrayList<com.qq.jce.vmarket.wmarket.AppDetail>)cache_appList).add(__var_31);
        }
        this.appList = (java.util.ArrayList<com.qq.jce.vmarket.wmarket.AppDetail>) _is.read(cache_appList, 7, false);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(type, "type");
        _ds.display(pkgName, "pkgName");
        _ds.display(downloadRateDesc, "downloadRateDesc");
        _ds.display(pkgNameList, "pkgNameList");
        _ds.display(topDesc, "topDesc");
        _ds.display(bottomDesc, "bottomDesc");
        _ds.display(appDetail, "appDetail");
        _ds.display(appList, "appList");
    }

    public void displaySimple(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.displaySimple(type, true);
        _ds.displaySimple(pkgName, true);
        _ds.displaySimple(downloadRateDesc, true);
        _ds.displaySimple(pkgNameList, true);
        _ds.displaySimple(topDesc, true);
        _ds.displaySimple(bottomDesc, true);
        _ds.displaySimple(appDetail, true);
        _ds.displaySimple(appList, false);
    }

}

