// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/noahyang/kvConfig.jce'
// **********************************************************************

package com.qq.jce.WCS_BASE;

public final class enumResultCode implements java.io.Serializable
{
    private static enumResultCode[] __values = new enumResultCode[36];
    private int __value;
    private String __T = new String();

    public static final int _RESULT_CODE_SUCCESS = 0;
    public static final enumResultCode RESULT_CODE_SUCCESS = new enumResultCode(0,_RESULT_CODE_SUCCESS,"RESULT_CODE_SUCCESS");
    public static final int _RESULT_CODE_PARAM_ERROR = 1;
    public static final enumResultCode RESULT_CODE_PARAM_ERROR = new enumResultCode(1,_RESULT_CODE_PARAM_ERROR,"RESULT_CODE_PARAM_ERROR");
    public static final int _RESULT_CODE_UNKNOWN = 65535;
    public static final enumResultCode RESULT_CODE_UNKNOWN = new enumResultCode(2,_RESULT_CODE_UNKNOWN,"RESULT_CODE_UNKNOWN");
    public static final int _RESULT_CODE_FORBIDDEN = 2;
    public static final enumResultCode RESULT_CODE_FORBIDDEN = new enumResultCode(3,_RESULT_CODE_FORBIDDEN,"RESULT_CODE_FORBIDDEN");
    public static final int _RESULT_CODE_EMPTY = 3;
    public static final enumResultCode RESULT_CODE_EMPTY = new enumResultCode(4,_RESULT_CODE_EMPTY,"RESULT_CODE_EMPTY");
    public static final int _RESULT_CODE_EXEC_FAILURE = 4;
    public static final enumResultCode RESULT_CODE_EXEC_FAILURE = new enumResultCode(5,_RESULT_CODE_EXEC_FAILURE,"RESULT_CODE_EXEC_FAILURE");
    public static final int _SESSION_RESULT_CODE_DCACHE_ERROR = 65537;
    public static final enumResultCode SESSION_RESULT_CODE_DCACHE_ERROR = new enumResultCode(6,_SESSION_RESULT_CODE_DCACHE_ERROR,"SESSION_RESULT_CODE_DCACHE_ERROR");
    public static final int _SESSION_RESULT_CODE_QR_TIMEOUT = 65538;
    public static final enumResultCode SESSION_RESULT_CODE_QR_TIMEOUT = new enumResultCode(7,_SESSION_RESULT_CODE_QR_TIMEOUT,"SESSION_RESULT_CODE_QR_TIMEOUT");
    public static final int _SESSION_RESULT_CODE_LOGIN_VERIFY_FAILURE = 65539;
    public static final enumResultCode SESSION_RESULT_CODE_LOGIN_VERIFY_FAILURE = new enumResultCode(8,_SESSION_RESULT_CODE_LOGIN_VERIFY_FAILURE,"SESSION_RESULT_CODE_LOGIN_VERIFY_FAILURE");
    public static final int _SESSION_RESULT_CODE_VERIFY_SENDER_FAILURE = 65540;
    public static final enumResultCode SESSION_RESULT_CODE_VERIFY_SENDER_FAILURE = new enumResultCode(9,_SESSION_RESULT_CODE_VERIFY_SENDER_FAILURE,"SESSION_RESULT_CODE_VERIFY_SENDER_FAILURE");
    public static final int _POLICY_RESULT_CODE_NOT_FOUND = 196609;
    public static final enumResultCode POLICY_RESULT_CODE_NOT_FOUND = new enumResultCode(10,_POLICY_RESULT_CODE_NOT_FOUND,"POLICY_RESULT_CODE_NOT_FOUND");
    public static final int _POLICY_RESULT_CODE_PARAM_ERROR = 196610;
    public static final enumResultCode POLICY_RESULT_CODE_PARAM_ERROR = new enumResultCode(11,_POLICY_RESULT_CODE_PARAM_ERROR,"POLICY_RESULT_CODE_PARAM_ERROR");
    public static final int _POLICY_RESULT_CODE_VERIFY_FAIL = 196611;
    public static final enumResultCode POLICY_RESULT_CODE_VERIFY_FAIL = new enumResultCode(12,_POLICY_RESULT_CODE_VERIFY_FAIL,"POLICY_RESULT_CODE_VERIFY_FAIL");
    public static final int _POLICY_RESULT_CODE_RULE_ExISTS = 196612;
    public static final enumResultCode POLICY_RESULT_CODE_RULE_ExISTS = new enumResultCode(13,_POLICY_RESULT_CODE_RULE_ExISTS,"POLICY_RESULT_CODE_RULE_ExISTS");
    public static final int _POLICY_RESULT_CODE_SPECFIC_INDEx = 196613;
    public static final enumResultCode POLICY_RESULT_CODE_SPECFIC_INDEx = new enumResultCode(14,_POLICY_RESULT_CODE_SPECFIC_INDEx,"POLICY_RESULT_CODE_SPECFIC_INDEx");
    public static final int _POLICY_RESULT_CODE_ADMIN_VERIFY_FAILURE = 196614;
    public static final enumResultCode POLICY_RESULT_CODE_ADMIN_VERIFY_FAILURE = new enumResultCode(15,_POLICY_RESULT_CODE_ADMIN_VERIFY_FAILURE,"POLICY_RESULT_CODE_ADMIN_VERIFY_FAILURE");
    public static final int _ROUTE_RESULT_CODE_NOT_ExIST = 327681;
    public static final enumResultCode ROUTE_RESULT_CODE_NOT_ExIST = new enumResultCode(16,_ROUTE_RESULT_CODE_NOT_ExIST,"ROUTE_RESULT_CODE_NOT_ExIST");
    public static final int _ROUTE_RESULT_CODE_ExIST = 327682;
    public static final enumResultCode ROUTE_RESULT_CODE_ExIST = new enumResultCode(17,_ROUTE_RESULT_CODE_ExIST,"ROUTE_RESULT_CODE_ExIST");
    public static final int _DATA_RESULT_CODE_DCACHE_ERROR = 458753;
    public static final enumResultCode DATA_RESULT_CODE_DCACHE_ERROR = new enumResultCode(18,_DATA_RESULT_CODE_DCACHE_ERROR,"DATA_RESULT_CODE_DCACHE_ERROR");
    public static final int _COMMAND_RESULT_CODE_ExCHANGE_KEY_FAILURE = 589825;
    public static final enumResultCode COMMAND_RESULT_CODE_ExCHANGE_KEY_FAILURE = new enumResultCode(19,_COMMAND_RESULT_CODE_ExCHANGE_KEY_FAILURE,"COMMAND_RESULT_CODE_ExCHANGE_KEY_FAILURE");
    public static final int _COMMAND_RESULT_CODE_NONE = 589826;
    public static final enumResultCode COMMAND_RESULT_CODE_NONE = new enumResultCode(20,_COMMAND_RESULT_CODE_NONE,"COMMAND_RESULT_CODE_NONE");
    public static final int _COMMAND_RESULT_CODE_REMOTE_OFFLINE = 589827;
    public static final enumResultCode COMMAND_RESULT_CODE_REMOTE_OFFLINE = new enumResultCode(21,_COMMAND_RESULT_CODE_REMOTE_OFFLINE,"COMMAND_RESULT_CODE_REMOTE_OFFLINE");
    public static final int _COMMAND_RESULT_CODE_NEED_ExCHANGE_KEY = 589828;
    public static final enumResultCode COMMAND_RESULT_CODE_NEED_ExCHANGE_KEY = new enumResultCode(22,_COMMAND_RESULT_CODE_NEED_ExCHANGE_KEY,"COMMAND_RESULT_CODE_NEED_ExCHANGE_KEY");
    public static final int _COMMAND_RESULT_CODE_SESSION_NOT_FOUND = 589829;
    public static final enumResultCode COMMAND_RESULT_CODE_SESSION_NOT_FOUND = new enumResultCode(23,_COMMAND_RESULT_CODE_SESSION_NOT_FOUND,"COMMAND_RESULT_CODE_SESSION_NOT_FOUND");
    public static final int _RESULT_CODE_CREATE_MMAP_NAME_ERROR = 1048577;
    public static final enumResultCode RESULT_CODE_CREATE_MMAP_NAME_ERROR = new enumResultCode(24,_RESULT_CODE_CREATE_MMAP_NAME_ERROR,"RESULT_CODE_CREATE_MMAP_NAME_ERROR");
    public static final int _RESULT_CODE_SET_LOCAL_STORAGE_FAILURE = 1048578;
    public static final enumResultCode RESULT_CODE_SET_LOCAL_STORAGE_FAILURE = new enumResultCode(25,_RESULT_CODE_SET_LOCAL_STORAGE_FAILURE,"RESULT_CODE_SET_LOCAL_STORAGE_FAILURE");
    public static final int _RESULT_CODE_DOWNLOAD_OFFSET_ERROR = 1048579;
    public static final enumResultCode RESULT_CODE_DOWNLOAD_OFFSET_ERROR = new enumResultCode(26,_RESULT_CODE_DOWNLOAD_OFFSET_ERROR,"RESULT_CODE_DOWNLOAD_OFFSET_ERROR");
    public static final int _RESULT_CODE_FILE_NOT_EXIST = 1048580;
    public static final enumResultCode RESULT_CODE_FILE_NOT_EXIST = new enumResultCode(27,_RESULT_CODE_FILE_NOT_EXIST,"RESULT_CODE_FILE_NOT_EXIST");
    public static final int _RESULT_CODE_DELETE_FILE_FAILURE = 1048581;
    public static final enumResultCode RESULT_CODE_DELETE_FILE_FAILURE = new enumResultCode(28,_RESULT_CODE_DELETE_FILE_FAILURE,"RESULT_CODE_DELETE_FILE_FAILURE");
    public static final int _RESULT_CODE_GET_LOCAL_STORAGE_FAILURE = 1048582;
    public static final enumResultCode RESULT_CODE_GET_LOCAL_STORAGE_FAILURE = new enumResultCode(29,_RESULT_CODE_GET_LOCAL_STORAGE_FAILURE,"RESULT_CODE_GET_LOCAL_STORAGE_FAILURE");
    public static final int _RESULT_CODE_SYNC_MMAP_DATA_FAILURE = 1048583;
    public static final enumResultCode RESULT_CODE_SYNC_MMAP_DATA_FAILURE = new enumResultCode(30,_RESULT_CODE_SYNC_MMAP_DATA_FAILURE,"RESULT_CODE_SYNC_MMAP_DATA_FAILURE");
    public static final int _RESULT_CODE_PACKAGE_LIST_EMPTY = 1048584;
    public static final enumResultCode RESULT_CODE_PACKAGE_LIST_EMPTY = new enumResultCode(31,_RESULT_CODE_PACKAGE_LIST_EMPTY,"RESULT_CODE_PACKAGE_LIST_EMPTY");
    public static final int _RESULT_CODE_FILE_LIST_EMPTY = 1048585;
    public static final enumResultCode RESULT_CODE_FILE_LIST_EMPTY = new enumResultCode(32,_RESULT_CODE_FILE_LIST_EMPTY,"RESULT_CODE_FILE_LIST_EMPTY");
    public static final int _RESULT_CODE_CREATE_PATH_FAILURE = 1048592;
    public static final enumResultCode RESULT_CODE_CREATE_PATH_FAILURE = new enumResultCode(33,_RESULT_CODE_CREATE_PATH_FAILURE,"RESULT_CODE_CREATE_PATH_FAILURE");
    public static final int _CONFIG_RESULT_CODE_NOT_FOUND = 1114113;
    public static final enumResultCode CONFIG_RESULT_CODE_NOT_FOUND = new enumResultCode(34,_CONFIG_RESULT_CODE_NOT_FOUND,"CONFIG_RESULT_CODE_NOT_FOUND");
    public static final int _RESULT_CODE_END = 10027008;
    public static final enumResultCode RESULT_CODE_END = new enumResultCode(35,_RESULT_CODE_END,"RESULT_CODE_END");

    public static enumResultCode convert(int val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].value() == val)
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public static enumResultCode convert(String val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].toString().equals(val))
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public int value()
    {
        return __value;
    }

    public String toString()
    {
        return __T;
    }

    private enumResultCode(int index, int val, String s)
    {
        __T = s;
        __value = val;
        __values[index] = this;
    }

}
