// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/noahyang/kvConfig.jce'
// **********************************************************************

package com.qq.jce.WCS_BASE;

public final class msg_type implements java.io.Serializable
{
    private static msg_type[] __values = new msg_type[2];
    private int __value;
    private String __T = new String();

    public static final int _message_type_request = 0;
    public static final msg_type message_type_request = new msg_type(0,_message_type_request,"message_type_request");
    public static final int _message_type_response = 1;
    public static final msg_type message_type_response = new msg_type(1,_message_type_response,"message_type_response");

    public static msg_type convert(int val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].value() == val)
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public static msg_type convert(String val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].toString().equals(val))
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public int value()
    {
        return __value;
    }

    public String toString()
    {
        return __T;
    }

    private msg_type(int index, int val, String s)
    {
        __T = s;
        __value = val;
        __values[index] = this;
    }

}
