// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/joycefang/QQTipsjce-web.jce'
// **********************************************************************

package com.qq.jce.WCS;

public final class AdminQQTipsResult extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "WCS.AdminQQTipsResult";
    }

    public String fullClassName()
    {
        return "com.qq.jce.WCS.AdminQQTipsResult";
    }

    public String sDesc = "";

    public int nIdx = 0;

    public int eStatus = 0;

    public com.qq.jce.WCS.QQTipsResult stTip = null;

    public long lLastEnableTime = 0;

    public String getSDesc()
    {
        return sDesc;
    }

    public void  setSDesc(String sDesc)
    {
        this.sDesc = sDesc;
    }

    public int getNIdx()
    {
        return nIdx;
    }

    public void  setNIdx(int nIdx)
    {
        this.nIdx = nIdx;
    }

    public int getEStatus()
    {
        return eStatus;
    }

    public void  setEStatus(int eStatus)
    {
        this.eStatus = eStatus;
    }

    public com.qq.jce.WCS.QQTipsResult getStTip()
    {
        return stTip;
    }

    public void  setStTip(com.qq.jce.WCS.QQTipsResult stTip)
    {
        this.stTip = stTip;
    }

    public long getLLastEnableTime()
    {
        return lLastEnableTime;
    }

    public void  setLLastEnableTime(long lLastEnableTime)
    {
        this.lLastEnableTime = lLastEnableTime;
    }

    public AdminQQTipsResult()
    {
    }

    public AdminQQTipsResult(String sDesc, int nIdx, int eStatus, com.qq.jce.WCS.QQTipsResult stTip, long lLastEnableTime)
    {
        this.sDesc = sDesc;
        this.nIdx = nIdx;
        this.eStatus = eStatus;
        this.stTip = stTip;
        this.lLastEnableTime = lLastEnableTime;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        AdminQQTipsResult t = (AdminQQTipsResult) o;
        return (
            com.qq.taf.jce.JceUtil.equals(sDesc, t.sDesc) && 
            com.qq.taf.jce.JceUtil.equals(nIdx, t.nIdx) && 
            com.qq.taf.jce.JceUtil.equals(eStatus, t.eStatus) && 
            com.qq.taf.jce.JceUtil.equals(stTip, t.stTip) && 
            com.qq.taf.jce.JceUtil.equals(lLastEnableTime, t.lLastEnableTime) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(sDesc, 0);
        _os.write(nIdx, 1);
        _os.write(eStatus, 2);
        _os.write(stTip, 3);
        _os.write(lLastEnableTime, 4);
    }

    static int cache_eStatus;
    static com.qq.jce.WCS.QQTipsResult cache_stTip;

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.sDesc =  _is.readString(0, true);
        this.nIdx = (int) _is.read(nIdx, 1, true);
        this.eStatus = (int) _is.read(eStatus, 2, true);
        if(null == cache_stTip)
        {
            cache_stTip = new com.qq.jce.WCS.QQTipsResult();
        }
        this.stTip = (com.qq.jce.WCS.QQTipsResult) _is.read(cache_stTip, 3, true);
        this.lLastEnableTime = (long) _is.read(lLastEnableTime, 4, true);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(sDesc, "sDesc");
        _ds.display(nIdx, "nIdx");
        _ds.display(eStatus, "eStatus");
        _ds.display(stTip, "stTip");
        _ds.display(lLastEnableTime, "lLastEnableTime");
    }

    public void displaySimple(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.displaySimple(sDesc, true);
        _ds.displaySimple(nIdx, true);
        _ds.displaySimple(eStatus, true);
        _ds.displaySimple(stTip, true);
        _ds.displaySimple(lLastEnableTime, false);
    }

}

