// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/noahyang/you.jce'
// **********************************************************************

package com.qq.jce.WCS;

public final class AppAssociateResponse extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "WCS.AppAssociateResponse";
    }

    public String fullClassName()
    {
        return "com.qq.jce.WCS.AppAssociateResponse";
    }

    public int eResultCode = 0;

    public java.util.ArrayList<com.qq.jce.MAAccess.AppDetail> vItems = null;

    public java.util.ArrayList<String> vKeywordsList = null;

    public int getEResultCode()
    {
        return eResultCode;
    }

    public void  setEResultCode(int eResultCode)
    {
        this.eResultCode = eResultCode;
    }

    public java.util.ArrayList<com.qq.jce.MAAccess.AppDetail> getVItems()
    {
        return vItems;
    }

    public void  setVItems(java.util.ArrayList<com.qq.jce.MAAccess.AppDetail> vItems)
    {
        this.vItems = vItems;
    }

    public java.util.ArrayList<String> getVKeywordsList()
    {
        return vKeywordsList;
    }

    public void  setVKeywordsList(java.util.ArrayList<String> vKeywordsList)
    {
        this.vKeywordsList = vKeywordsList;
    }

    public AppAssociateResponse()
    {
    }

    public AppAssociateResponse(int eResultCode, java.util.ArrayList<com.qq.jce.MAAccess.AppDetail> vItems, java.util.ArrayList<String> vKeywordsList)
    {
        this.eResultCode = eResultCode;
        this.vItems = vItems;
        this.vKeywordsList = vKeywordsList;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        AppAssociateResponse t = (AppAssociateResponse) o;
        return (
            com.qq.taf.jce.JceUtil.equals(eResultCode, t.eResultCode) && 
            com.qq.taf.jce.JceUtil.equals(vItems, t.vItems) && 
            com.qq.taf.jce.JceUtil.equals(vKeywordsList, t.vKeywordsList) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(eResultCode, 0);
        _os.write(vItems, 1);
        _os.write(vKeywordsList, 2);
    }

    static int cache_eResultCode;
    static java.util.ArrayList<com.qq.jce.MAAccess.AppDetail> cache_vItems;
    static java.util.ArrayList<String> cache_vKeywordsList;

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.eResultCode = (int) _is.read(eResultCode, 0, true);
        if(null == cache_vItems)
        {
            cache_vItems = new java.util.ArrayList<com.qq.jce.MAAccess.AppDetail>();
            com.qq.jce.MAAccess.AppDetail __var_39 = new com.qq.jce.MAAccess.AppDetail();
            ((java.util.ArrayList<com.qq.jce.MAAccess.AppDetail>)cache_vItems).add(__var_39);
        }
        this.vItems = (java.util.ArrayList<com.qq.jce.MAAccess.AppDetail>) _is.read(cache_vItems, 1, true);
        if(null == cache_vKeywordsList)
        {
            cache_vKeywordsList = new java.util.ArrayList<String>();
            String __var_40 = "";
            ((java.util.ArrayList<String>)cache_vKeywordsList).add(__var_40);
        }
        this.vKeywordsList = (java.util.ArrayList<String>) _is.read(cache_vKeywordsList, 2, true);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(eResultCode, "eResultCode");
        _ds.display(vItems, "vItems");
        _ds.display(vKeywordsList, "vKeywordsList");
    }

    public void displaySimple(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.displaySimple(eResultCode, true);
        _ds.displaySimple(vItems, true);
        _ds.displaySimple(vKeywordsList, false);
    }

}

