// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/noahyang/you.jce'
// **********************************************************************

package com.qq.jce.WCS;

public final class AppUpdateInfo extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "WCS.AppUpdateInfo";
    }

    public String fullClassName()
    {
        return "com.qq.jce.WCS.AppUpdateInfo";
    }

    public String sPackage = "";

    public String sApkName = "";

    public String sNewVersionName = "";

    public int nNewVersionCode = 0;

    public String sApkDownUrl = "";

    public String sIconUrl = "";

    public String getSPackage()
    {
        return sPackage;
    }

    public void  setSPackage(String sPackage)
    {
        this.sPackage = sPackage;
    }

    public String getSApkName()
    {
        return sApkName;
    }

    public void  setSApkName(String sApkName)
    {
        this.sApkName = sApkName;
    }

    public String getSNewVersionName()
    {
        return sNewVersionName;
    }

    public void  setSNewVersionName(String sNewVersionName)
    {
        this.sNewVersionName = sNewVersionName;
    }

    public int getNNewVersionCode()
    {
        return nNewVersionCode;
    }

    public void  setNNewVersionCode(int nNewVersionCode)
    {
        this.nNewVersionCode = nNewVersionCode;
    }

    public String getSApkDownUrl()
    {
        return sApkDownUrl;
    }

    public void  setSApkDownUrl(String sApkDownUrl)
    {
        this.sApkDownUrl = sApkDownUrl;
    }

    public String getSIconUrl()
    {
        return sIconUrl;
    }

    public void  setSIconUrl(String sIconUrl)
    {
        this.sIconUrl = sIconUrl;
    }

    public AppUpdateInfo()
    {
    }

    public AppUpdateInfo(String sPackage, String sApkName, String sNewVersionName, int nNewVersionCode, String sApkDownUrl, String sIconUrl)
    {
        this.sPackage = sPackage;
        this.sApkName = sApkName;
        this.sNewVersionName = sNewVersionName;
        this.nNewVersionCode = nNewVersionCode;
        this.sApkDownUrl = sApkDownUrl;
        this.sIconUrl = sIconUrl;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        AppUpdateInfo t = (AppUpdateInfo) o;
        return (
            com.qq.taf.jce.JceUtil.equals(sPackage, t.sPackage) && 
            com.qq.taf.jce.JceUtil.equals(sApkName, t.sApkName) && 
            com.qq.taf.jce.JceUtil.equals(sNewVersionName, t.sNewVersionName) && 
            com.qq.taf.jce.JceUtil.equals(nNewVersionCode, t.nNewVersionCode) && 
            com.qq.taf.jce.JceUtil.equals(sApkDownUrl, t.sApkDownUrl) && 
            com.qq.taf.jce.JceUtil.equals(sIconUrl, t.sIconUrl) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(sPackage, 0);
        _os.write(sApkName, 1);
        _os.write(sNewVersionName, 2);
        _os.write(nNewVersionCode, 3);
        _os.write(sApkDownUrl, 4);
        _os.write(sIconUrl, 5);
    }


    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.sPackage =  _is.readString(0, true);
        this.sApkName =  _is.readString(1, true);
        this.sNewVersionName =  _is.readString(2, true);
        this.nNewVersionCode = (int) _is.read(nNewVersionCode, 3, true);
        this.sApkDownUrl =  _is.readString(4, true);
        this.sIconUrl =  _is.readString(5, true);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(sPackage, "sPackage");
        _ds.display(sApkName, "sApkName");
        _ds.display(sNewVersionName, "sNewVersionName");
        _ds.display(nNewVersionCode, "nNewVersionCode");
        _ds.display(sApkDownUrl, "sApkDownUrl");
        _ds.display(sIconUrl, "sIconUrl");
    }

    public void displaySimple(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.displaySimple(sPackage, true);
        _ds.displaySimple(sApkName, true);
        _ds.displaySimple(sNewVersionName, true);
        _ds.displaySimple(nNewVersionCode, true);
        _ds.displaySimple(sApkDownUrl, true);
        _ds.displaySimple(sIconUrl, false);
    }

}

