// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/noahyang/you.jce'
// **********************************************************************

package com.qq.jce.WCS;

public final class AppUpdateStatistics extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "WCS.AppUpdateStatistics";
    }

    public String fullClassName()
    {
        return "com.qq.jce.WCS.AppUpdateStatistics";
    }

    public int nTotalCount = 0;

    public int nUpdateCount = 0;

    public int getNTotalCount()
    {
        return nTotalCount;
    }

    public void  setNTotalCount(int nTotalCount)
    {
        this.nTotalCount = nTotalCount;
    }

    public int getNUpdateCount()
    {
        return nUpdateCount;
    }

    public void  setNUpdateCount(int nUpdateCount)
    {
        this.nUpdateCount = nUpdateCount;
    }

    public AppUpdateStatistics()
    {
    }

    public AppUpdateStatistics(int nTotalCount, int nUpdateCount)
    {
        this.nTotalCount = nTotalCount;
        this.nUpdateCount = nUpdateCount;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        AppUpdateStatistics t = (AppUpdateStatistics) o;
        return (
            com.qq.taf.jce.JceUtil.equals(nTotalCount, t.nTotalCount) && 
            com.qq.taf.jce.JceUtil.equals(nUpdateCount, t.nUpdateCount) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(nTotalCount, 0);
        _os.write(nUpdateCount, 1);
    }


    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.nTotalCount = (int) _is.read(nTotalCount, 0, true);
        this.nUpdateCount = (int) _is.read(nUpdateCount, 1, true);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(nTotalCount, "nTotalCount");
        _ds.display(nUpdateCount, "nUpdateCount");
    }

    public void displaySimple(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.displaySimple(nTotalCount, true);
        _ds.displaySimple(nUpdateCount, false);
    }

}

