// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/noahyang/you.jce'
// **********************************************************************

package com.qq.jce.WCS;

public final class BaseInfoRequest extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "WCS.BaseInfoRequest";
    }

    public String fullClassName()
    {
        return "com.qq.jce.WCS.BaseInfoRequest";
    }

    public String sSrcIp = "";

    public String getSSrcIp()
    {
        return sSrcIp;
    }

    public void  setSSrcIp(String sSrcIp)
    {
        this.sSrcIp = sSrcIp;
    }

    public BaseInfoRequest()
    {
    }

    public BaseInfoRequest(String sSrcIp)
    {
        this.sSrcIp = sSrcIp;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        BaseInfoRequest t = (BaseInfoRequest) o;
        return (
            com.qq.taf.jce.JceUtil.equals(sSrcIp, t.sSrcIp) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(sSrcIp, 0);
    }


    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.sSrcIp =  _is.readString(0, true);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(sSrcIp, "sSrcIp");
    }

    public void displaySimple(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.displaySimple(sSrcIp, false);
    }

}

