// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/noahyang/dock.jce'
// **********************************************************************

package com.qq.jce.WCS;

public final class ConnUnitStatus implements java.io.Serializable
{
    private static ConnUnitStatus[] __values = new ConnUnitStatus[2];
    private int __value;
    private String __T = new String();

    public static final int _CUS_ENABLE = 0;
    public static final ConnUnitStatus CUS_ENABLE = new ConnUnitStatus(0,_CUS_ENABLE,"CUS_ENABLE");
    public static final int _CUS_DISABLE = 1;
    public static final ConnUnitStatus CUS_DISABLE = new ConnUnitStatus(1,_CUS_DISABLE,"CUS_DISABLE");

    public static ConnUnitStatus convert(int val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].value() == val)
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public static ConnUnitStatus convert(String val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].toString().equals(val))
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public int value()
    {
        return __value;
    }

    public String toString()
    {
        return __T;
    }

    private ConnUnitStatus(int index, int val, String s)
    {
        __T = s;
        __value = val;
        __values[index] = this;
    }

}
