// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/noahyang/dock.jce'
// **********************************************************************

package com.qq.jce.WCS;

public final class E_DockInfoStatus implements java.io.Serializable
{
    private static E_DockInfoStatus[] __values = new E_DockInfoStatus[2];
    private int __value;
    private String __T = new String();

    public static final int _E_DOCK_INFO_STATUS_ENABLE = 0;
    public static final E_DockInfoStatus E_DOCK_INFO_STATUS_ENABLE = new E_DockInfoStatus(0,_E_DOCK_INFO_STATUS_ENABLE,"E_DOCK_INFO_STATUS_ENABLE");
    public static final int _E_DOCK_INFO_STATUS_DISABLE = 1;
    public static final E_DockInfoStatus E_DOCK_INFO_STATUS_DISABLE = new E_DockInfoStatus(1,_E_DOCK_INFO_STATUS_DISABLE,"E_DOCK_INFO_STATUS_DISABLE");

    public static E_DockInfoStatus convert(int val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].value() == val)
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public static E_DockInfoStatus convert(String val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].toString().equals(val))
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public int value()
    {
        return __value;
    }

    public String toString()
    {
        return __T;
    }

    private E_DockInfoStatus(int index, int val, String s)
    {
        __T = s;
        __value = val;
        __values[index] = this;
    }

}
