// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/noahyang/dock.jce'
// **********************************************************************

package com.qq.jce.WCS;

public final class enumBType implements java.io.Serializable
{
    private static enumBType[] __values = new enumBType[17];
    private int __value;
    private String __T = new String();

    public static final int _BTYPE_UPDATE = 0;
    public static final enumBType BTYPE_UPDATE = new enumBType(0,_BTYPE_UPDATE,"BTYPE_UPDATE");
    public static final int _BTYPE_FIX = 1;
    public static final enumBType BTYPE_FIX = new enumBType(1,_BTYPE_FIX,"BTYPE_FIX");
    public static final int _BTYE_COMPONENT = 2;
    public static final enumBType BTYE_COMPONENT = new enumBType(2,_BTYE_COMPONENT,"BTYE_COMPONENT");
    public static final int _BYTE_VERIFY = 3;
    public static final enumBType BYTE_VERIFY = new enumBType(3,_BYTE_VERIFY,"BYTE_VERIFY");
    public static final int _BYTE_FEATURERECOMMDATION = 4;
    public static final enumBType BYTE_FEATURERECOMMDATION = new enumBType(4,_BYTE_FEATURERECOMMDATION,"BYTE_FEATURERECOMMDATION");
    public static final int _BYTE_DOCKINFO = 5;
    public static final enumBType BYTE_DOCKINFO = new enumBType(5,_BYTE_DOCKINFO,"BYTE_DOCKINFO");
    public static final int _BYTE_DOCK_PRE_DL_INFO = 6;
    public static final enumBType BYTE_DOCK_PRE_DL_INFO = new enumBType(6,_BYTE_DOCK_PRE_DL_INFO,"BYTE_DOCK_PRE_DL_INFO");
    public static final int _BYTE_DOCK_UNIT_CONN_INFO = 7;
    public static final enumBType BYTE_DOCK_UNIT_CONN_INFO = new enumBType(7,_BYTE_DOCK_UNIT_CONN_INFO,"BYTE_DOCK_UNIT_CONN_INFO");
    public static final int _BYTE_LAGREPORTINFO = 8;
    public static final enumBType BYTE_LAGREPORTINFO = new enumBType(8,_BYTE_LAGREPORTINFO,"BYTE_LAGREPORTINFO");
    public static final int _BYTE_VIRTUAL_VERSION = 9;
    public static final enumBType BYTE_VIRTUAL_VERSION = new enumBType(9,_BYTE_VIRTUAL_VERSION,"BYTE_VIRTUAL_VERSION");
    public static final int _BYTE_CLIENT_UPDATE = 10;
    public static final enumBType BYTE_CLIENT_UPDATE = new enumBType(10,_BYTE_CLIENT_UPDATE,"BYTE_CLIENT_UPDATE");
    public static final int _BYTE_CLIENT_COMPONENT = 11;
    public static final enumBType BYTE_CLIENT_COMPONENT = new enumBType(11,_BYTE_CLIENT_COMPONENT,"BYTE_CLIENT_COMPONENT");
    public static final int _BYTE_SMART_ACTION = 12;
    public static final enumBType BYTE_SMART_ACTION = new enumBType(12,_BYTE_SMART_ACTION,"BYTE_SMART_ACTION");
    public static final int _BYTE_CONN_SERVICE_INVALID = 13;
    public static final enumBType BYTE_CONN_SERVICE_INVALID = new enumBType(13,_BYTE_CONN_SERVICE_INVALID,"BYTE_CONN_SERVICE_INVALID");
    public static final int _BYTE_HD = 14;
    public static final enumBType BYTE_HD = new enumBType(14,_BYTE_HD,"BYTE_HD");
    public static final int _BYTE_HDP = 15;
    public static final enumBType BYTE_HDP = new enumBType(15,_BYTE_HDP,"BYTE_HDP");
    public static final int _BYTE_MDB = 16;
    public static final enumBType BYTE_MDB = new enumBType(16,_BYTE_MDB,"BYTE_MDB");

    public static enumBType convert(int val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].value() == val)
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public static enumBType convert(String val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].toString().equals(val))
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public int value()
    {
        return __value;
    }

    public String toString()
    {
        return __T;
    }

    private enumBType(int index, int val, String s)
    {
        __T = s;
        __value = val;
        __values[index] = this;
    }

}
