// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/noahyang/mainProgram.jce'
// **********************************************************************

package com.qq.jce.WCS;

public final class enumClientUpdateType implements java.io.Serializable
{
    private static enumClientUpdateType[] __values = new enumClientUpdateType[4];
    private int __value;
    private String __T = new String();

    public static final int _CLIENT_UPDATE_TYPE_UNKNOWN = 0;
    public static final enumClientUpdateType CLIENT_UPDATE_TYPE_UNKNOWN = new enumClientUpdateType(0,_CLIENT_UPDATE_TYPE_UNKNOWN,"CLIENT_UPDATE_TYPE_UNKNOWN");
    public static final int _CLIENT_UPDATE_TYPE_FORCE = 1;
    public static final enumClientUpdateType CLIENT_UPDATE_TYPE_FORCE = new enumClientUpdateType(1,_CLIENT_UPDATE_TYPE_FORCE,"CLIENT_UPDATE_TYPE_FORCE");
    public static final int _CLIENT_UPDATE_TYPE_NONFORCE = 2;
    public static final enumClientUpdateType CLIENT_UPDATE_TYPE_NONFORCE = new enumClientUpdateType(2,_CLIENT_UPDATE_TYPE_NONFORCE,"CLIENT_UPDATE_TYPE_NONFORCE");
    public static final int _CLIENT_UPDATE_TYPE_SILENCE = 3;
    public static final enumClientUpdateType CLIENT_UPDATE_TYPE_SILENCE = new enumClientUpdateType(3,_CLIENT_UPDATE_TYPE_SILENCE,"CLIENT_UPDATE_TYPE_SILENCE");

    public static enumClientUpdateType convert(int val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].value() == val)
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public static enumClientUpdateType convert(String val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].toString().equals(val))
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public int value()
    {
        return __value;
    }

    public String toString()
    {
        return __T;
    }

    private enumClientUpdateType(int index, int val, String s)
    {
        __T = s;
        __value = val;
        __values[index] = this;
    }

}
