// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/noahyang/connServiceInvalid.jce'
// **********************************************************************

package com.qq.jce.WCS;

public final class enumUpdateType implements java.io.Serializable
{
    private static enumUpdateType[] __values = new enumUpdateType[4];
    private int __value;
    private String __T = new String();

    public static final int _UPDATE_TYPE_UNKNOW = 0;
    public static final enumUpdateType UPDATE_TYPE_UNKNOW = new enumUpdateType(0,_UPDATE_TYPE_UNKNOW,"UPDATE_TYPE_UNKNOW");
    public static final int _UPDATE_TYPE_AUTO = 1;
    public static final enumUpdateType UPDATE_TYPE_AUTO = new enumUpdateType(1,_UPDATE_TYPE_AUTO,"UPDATE_TYPE_AUTO");
    public static final int _UPDATE_TYPE_SILENCE = 2;
    public static final enumUpdateType UPDATE_TYPE_SILENCE = new enumUpdateType(2,_UPDATE_TYPE_SILENCE,"UPDATE_TYPE_SILENCE");
    public static final int _UPDATE_TYPE_FORCE = 3;
    public static final enumUpdateType UPDATE_TYPE_FORCE = new enumUpdateType(3,_UPDATE_TYPE_FORCE,"UPDATE_TYPE_FORCE");

    public static enumUpdateType convert(int val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].value() == val)
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public static enumUpdateType convert(String val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].toString().equals(val))
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public int value()
    {
        return __value;
    }

    public String toString()
    {
        return __T;
    }

    private enumUpdateType(int index, int val, String s)
    {
        __T = s;
        __value = val;
        __values[index] = this;
    }

}
