// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/joycefang/QQTipsjce-web.jce'
// **********************************************************************

package com.qq.jce.WCS;

public final class FirstReleaseAppInfo extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "WCS.FirstReleaseAppInfo";
    }

    public String fullClassName()
    {
        return "com.qq.jce.WCS.FirstReleaseAppInfo";
    }

    public String sTitle = "";

    public String sContent = "";

    public String sPicUrl = "";

    public short nPriority = 0;

    public int nTipId = 0;

    public String sApkName = "";

    public String sApkPackName = "";

    public String sApkVersion = "";

    public String sApkDlUrl = "";

    public String getSTitle()
    {
        return sTitle;
    }

    public void  setSTitle(String sTitle)
    {
        this.sTitle = sTitle;
    }

    public String getSContent()
    {
        return sContent;
    }

    public void  setSContent(String sContent)
    {
        this.sContent = sContent;
    }

    public String getSPicUrl()
    {
        return sPicUrl;
    }

    public void  setSPicUrl(String sPicUrl)
    {
        this.sPicUrl = sPicUrl;
    }

    public short getNPriority()
    {
        return nPriority;
    }

    public void  setNPriority(short nPriority)
    {
        this.nPriority = nPriority;
    }

    public int getNTipId()
    {
        return nTipId;
    }

    public void  setNTipId(int nTipId)
    {
        this.nTipId = nTipId;
    }

    public String getSApkName()
    {
        return sApkName;
    }

    public void  setSApkName(String sApkName)
    {
        this.sApkName = sApkName;
    }

    public String getSApkPackName()
    {
        return sApkPackName;
    }

    public void  setSApkPackName(String sApkPackName)
    {
        this.sApkPackName = sApkPackName;
    }

    public String getSApkVersion()
    {
        return sApkVersion;
    }

    public void  setSApkVersion(String sApkVersion)
    {
        this.sApkVersion = sApkVersion;
    }

    public String getSApkDlUrl()
    {
        return sApkDlUrl;
    }

    public void  setSApkDlUrl(String sApkDlUrl)
    {
        this.sApkDlUrl = sApkDlUrl;
    }

    public FirstReleaseAppInfo()
    {
    }

    public FirstReleaseAppInfo(String sTitle, String sContent, String sPicUrl, short nPriority, int nTipId, String sApkName, String sApkPackName, String sApkVersion, String sApkDlUrl)
    {
        this.sTitle = sTitle;
        this.sContent = sContent;
        this.sPicUrl = sPicUrl;
        this.nPriority = nPriority;
        this.nTipId = nTipId;
        this.sApkName = sApkName;
        this.sApkPackName = sApkPackName;
        this.sApkVersion = sApkVersion;
        this.sApkDlUrl = sApkDlUrl;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        FirstReleaseAppInfo t = (FirstReleaseAppInfo) o;
        return (
            com.qq.taf.jce.JceUtil.equals(sTitle, t.sTitle) && 
            com.qq.taf.jce.JceUtil.equals(sContent, t.sContent) && 
            com.qq.taf.jce.JceUtil.equals(sPicUrl, t.sPicUrl) && 
            com.qq.taf.jce.JceUtil.equals(nPriority, t.nPriority) && 
            com.qq.taf.jce.JceUtil.equals(nTipId, t.nTipId) && 
            com.qq.taf.jce.JceUtil.equals(sApkName, t.sApkName) && 
            com.qq.taf.jce.JceUtil.equals(sApkPackName, t.sApkPackName) && 
            com.qq.taf.jce.JceUtil.equals(sApkVersion, t.sApkVersion) && 
            com.qq.taf.jce.JceUtil.equals(sApkDlUrl, t.sApkDlUrl) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(sTitle, 0);
        _os.write(sContent, 1);
        _os.write(sPicUrl, 2);
        _os.write(nPriority, 3);
        _os.write(nTipId, 4);
        _os.write(sApkName, 5);
        _os.write(sApkPackName, 6);
        _os.write(sApkVersion, 7);
        _os.write(sApkDlUrl, 8);
    }


    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.sTitle =  _is.readString(0, true);
        this.sContent =  _is.readString(1, true);
        this.sPicUrl =  _is.readString(2, true);
        this.nPriority = (short) _is.read(nPriority, 3, true);
        this.nTipId = (int) _is.read(nTipId, 4, true);
        this.sApkName =  _is.readString(5, true);
        this.sApkPackName =  _is.readString(6, true);
        this.sApkVersion =  _is.readString(7, true);
        this.sApkDlUrl =  _is.readString(8, true);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(sTitle, "sTitle");
        _ds.display(sContent, "sContent");
        _ds.display(sPicUrl, "sPicUrl");
        _ds.display(nPriority, "nPriority");
        _ds.display(nTipId, "nTipId");
        _ds.display(sApkName, "sApkName");
        _ds.display(sApkPackName, "sApkPackName");
        _ds.display(sApkVersion, "sApkVersion");
        _ds.display(sApkDlUrl, "sApkDlUrl");
    }

    public void displaySimple(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.displaySimple(sTitle, true);
        _ds.displaySimple(sContent, true);
        _ds.displaySimple(sPicUrl, true);
        _ds.displaySimple(nPriority, true);
        _ds.displaySimple(nTipId, true);
        _ds.displaySimple(sApkName, true);
        _ds.displaySimple(sApkPackName, true);
        _ds.displaySimple(sApkVersion, true);
        _ds.displaySimple(sApkDlUrl, false);
    }

}

