// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/noahyang/dock.jce'
// **********************************************************************

package com.qq.jce.WCS;

public final class ModifyDockPreDlInfoRequest extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "WCS.ModifyDockPreDlInfoRequest";
    }

    public String fullClassName()
    {
        return "com.qq.jce.WCS.ModifyDockPreDlInfoRequest";
    }

    public com.qq.jce.WCS.AdminRequest stAdminRequestInfo = null;

    public java.util.Map<String, java.util.ArrayList<String>> mapUnit = null;

    public com.qq.jce.WCS.DockPreDlInfoElem stInfo = null;

    public long lReleaseTime = 0;

    public long lQueryLimit = 0;

    public int nEnablePeriod = 0;

    public com.qq.jce.WCS.AdminRequest getStAdminRequestInfo()
    {
        return stAdminRequestInfo;
    }

    public void  setStAdminRequestInfo(com.qq.jce.WCS.AdminRequest stAdminRequestInfo)
    {
        this.stAdminRequestInfo = stAdminRequestInfo;
    }

    public java.util.Map<String, java.util.ArrayList<String>> getMapUnit()
    {
        return mapUnit;
    }

    public void  setMapUnit(java.util.Map<String, java.util.ArrayList<String>> mapUnit)
    {
        this.mapUnit = mapUnit;
    }

    public com.qq.jce.WCS.DockPreDlInfoElem getStInfo()
    {
        return stInfo;
    }

    public void  setStInfo(com.qq.jce.WCS.DockPreDlInfoElem stInfo)
    {
        this.stInfo = stInfo;
    }

    public long getLReleaseTime()
    {
        return lReleaseTime;
    }

    public void  setLReleaseTime(long lReleaseTime)
    {
        this.lReleaseTime = lReleaseTime;
    }

    public long getLQueryLimit()
    {
        return lQueryLimit;
    }

    public void  setLQueryLimit(long lQueryLimit)
    {
        this.lQueryLimit = lQueryLimit;
    }

    public int getNEnablePeriod()
    {
        return nEnablePeriod;
    }

    public void  setNEnablePeriod(int nEnablePeriod)
    {
        this.nEnablePeriod = nEnablePeriod;
    }

    public ModifyDockPreDlInfoRequest()
    {
    }

    public ModifyDockPreDlInfoRequest(com.qq.jce.WCS.AdminRequest stAdminRequestInfo, java.util.Map<String, java.util.ArrayList<String>> mapUnit, com.qq.jce.WCS.DockPreDlInfoElem stInfo, long lReleaseTime, long lQueryLimit, int nEnablePeriod)
    {
        this.stAdminRequestInfo = stAdminRequestInfo;
        this.mapUnit = mapUnit;
        this.stInfo = stInfo;
        this.lReleaseTime = lReleaseTime;
        this.lQueryLimit = lQueryLimit;
        this.nEnablePeriod = nEnablePeriod;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        ModifyDockPreDlInfoRequest t = (ModifyDockPreDlInfoRequest) o;
        return (
            com.qq.taf.jce.JceUtil.equals(stAdminRequestInfo, t.stAdminRequestInfo) && 
            com.qq.taf.jce.JceUtil.equals(mapUnit, t.mapUnit) && 
            com.qq.taf.jce.JceUtil.equals(stInfo, t.stInfo) && 
            com.qq.taf.jce.JceUtil.equals(lReleaseTime, t.lReleaseTime) && 
            com.qq.taf.jce.JceUtil.equals(lQueryLimit, t.lQueryLimit) && 
            com.qq.taf.jce.JceUtil.equals(nEnablePeriod, t.nEnablePeriod) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(stAdminRequestInfo, 0);
        _os.write(mapUnit, 1);
        _os.write(stInfo, 2);
        _os.write(lReleaseTime, 3);
        _os.write(lQueryLimit, 4);
        _os.write(nEnablePeriod, 5);
    }

    static com.qq.jce.WCS.AdminRequest cache_stAdminRequestInfo;
    static java.util.Map<String, java.util.ArrayList<String>> cache_mapUnit;
    static com.qq.jce.WCS.DockPreDlInfoElem cache_stInfo;

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        if(null == cache_stAdminRequestInfo)
        {
            cache_stAdminRequestInfo = new com.qq.jce.WCS.AdminRequest();
        }
        this.stAdminRequestInfo = (com.qq.jce.WCS.AdminRequest) _is.read(cache_stAdminRequestInfo, 0, true);
        if(null == cache_mapUnit)
        {
            cache_mapUnit = new java.util.HashMap<String, java.util.ArrayList<String>>();
            String __var_15 = "";
            java.util.ArrayList<String> __var_16 = new java.util.ArrayList<String>();
            String __var_17 = "";
            ((java.util.ArrayList<String>)__var_16).add(__var_17);
            cache_mapUnit.put(__var_15, __var_16);
        }
        this.mapUnit = (java.util.Map<String, java.util.ArrayList<String>>) _is.read(cache_mapUnit, 1, true);
        if(null == cache_stInfo)
        {
            cache_stInfo = new com.qq.jce.WCS.DockPreDlInfoElem();
        }
        this.stInfo = (com.qq.jce.WCS.DockPreDlInfoElem) _is.read(cache_stInfo, 2, true);
        this.lReleaseTime = (long) _is.read(lReleaseTime, 3, false);
        this.lQueryLimit = (long) _is.read(lQueryLimit, 4, false);
        this.nEnablePeriod = (int) _is.read(nEnablePeriod, 5, false);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(stAdminRequestInfo, "stAdminRequestInfo");
        _ds.display(mapUnit, "mapUnit");
        _ds.display(stInfo, "stInfo");
        _ds.display(lReleaseTime, "lReleaseTime");
        _ds.display(lQueryLimit, "lQueryLimit");
        _ds.display(nEnablePeriod, "nEnablePeriod");
    }

    public void displaySimple(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.displaySimple(stAdminRequestInfo, true);
        _ds.displaySimple(mapUnit, true);
        _ds.displaySimple(stInfo, true);
        _ds.displaySimple(lReleaseTime, true);
        _ds.displaySimple(lQueryLimit, true);
        _ds.displaySimple(nEnablePeriod, false);
    }

}

