// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/noahyang/connServiceInvalid.jce'
// **********************************************************************

package com.qq.jce.WCS;

public final class ModifyComponentInfoRequest extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "WCS.ModifyComponentInfoRequest";
    }

    public String fullClassName()
    {
        return "com.qq.jce.WCS.ModifyComponentInfoRequest";
    }

    public String sMsg = "";

    public java.util.Map<String, java.util.ArrayList<String>> mapUnit = null;

    public java.util.ArrayList<com.qq.jce.WCS.ComponentUnitInfo> vecComponents = null;

    public com.qq.jce.WCS.AdminRequest stAdminRequestInfo = null;

    public long lReleaseTime = 0;

    public String sRuleDesc = "";

    public long lUpdateLimit = 0;

    public int nEnablePeriod = 0;

    public String getSMsg()
    {
        return sMsg;
    }

    public void  setSMsg(String sMsg)
    {
        this.sMsg = sMsg;
    }

    public java.util.Map<String, java.util.ArrayList<String>> getMapUnit()
    {
        return mapUnit;
    }

    public void  setMapUnit(java.util.Map<String, java.util.ArrayList<String>> mapUnit)
    {
        this.mapUnit = mapUnit;
    }

    public java.util.ArrayList<com.qq.jce.WCS.ComponentUnitInfo> getVecComponents()
    {
        return vecComponents;
    }

    public void  setVecComponents(java.util.ArrayList<com.qq.jce.WCS.ComponentUnitInfo> vecComponents)
    {
        this.vecComponents = vecComponents;
    }

    public com.qq.jce.WCS.AdminRequest getStAdminRequestInfo()
    {
        return stAdminRequestInfo;
    }

    public void  setStAdminRequestInfo(com.qq.jce.WCS.AdminRequest stAdminRequestInfo)
    {
        this.stAdminRequestInfo = stAdminRequestInfo;
    }

    public long getLReleaseTime()
    {
        return lReleaseTime;
    }

    public void  setLReleaseTime(long lReleaseTime)
    {
        this.lReleaseTime = lReleaseTime;
    }

    public String getSRuleDesc()
    {
        return sRuleDesc;
    }

    public void  setSRuleDesc(String sRuleDesc)
    {
        this.sRuleDesc = sRuleDesc;
    }

    public long getLUpdateLimit()
    {
        return lUpdateLimit;
    }

    public void  setLUpdateLimit(long lUpdateLimit)
    {
        this.lUpdateLimit = lUpdateLimit;
    }

    public int getNEnablePeriod()
    {
        return nEnablePeriod;
    }

    public void  setNEnablePeriod(int nEnablePeriod)
    {
        this.nEnablePeriod = nEnablePeriod;
    }

    public ModifyComponentInfoRequest()
    {
    }

    public ModifyComponentInfoRequest(String sMsg, java.util.Map<String, java.util.ArrayList<String>> mapUnit, java.util.ArrayList<com.qq.jce.WCS.ComponentUnitInfo> vecComponents, com.qq.jce.WCS.AdminRequest stAdminRequestInfo, long lReleaseTime, String sRuleDesc, long lUpdateLimit, int nEnablePeriod)
    {
        this.sMsg = sMsg;
        this.mapUnit = mapUnit;
        this.vecComponents = vecComponents;
        this.stAdminRequestInfo = stAdminRequestInfo;
        this.lReleaseTime = lReleaseTime;
        this.sRuleDesc = sRuleDesc;
        this.lUpdateLimit = lUpdateLimit;
        this.nEnablePeriod = nEnablePeriod;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        ModifyComponentInfoRequest t = (ModifyComponentInfoRequest) o;
        return (
            com.qq.taf.jce.JceUtil.equals(sMsg, t.sMsg) && 
            com.qq.taf.jce.JceUtil.equals(mapUnit, t.mapUnit) && 
            com.qq.taf.jce.JceUtil.equals(vecComponents, t.vecComponents) && 
            com.qq.taf.jce.JceUtil.equals(stAdminRequestInfo, t.stAdminRequestInfo) && 
            com.qq.taf.jce.JceUtil.equals(lReleaseTime, t.lReleaseTime) && 
            com.qq.taf.jce.JceUtil.equals(sRuleDesc, t.sRuleDesc) && 
            com.qq.taf.jce.JceUtil.equals(lUpdateLimit, t.lUpdateLimit) && 
            com.qq.taf.jce.JceUtil.equals(nEnablePeriod, t.nEnablePeriod) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(sMsg, 0);
        _os.write(mapUnit, 1);
        _os.write(vecComponents, 2);
        _os.write(stAdminRequestInfo, 3);
        _os.write(lReleaseTime, 4);
        if (null != sRuleDesc)
        {
            _os.write(sRuleDesc, 5);
        }
        _os.write(lUpdateLimit, 6);
        _os.write(nEnablePeriod, 7);
    }

    static java.util.Map<String, java.util.ArrayList<String>> cache_mapUnit;
    static java.util.ArrayList<com.qq.jce.WCS.ComponentUnitInfo> cache_vecComponents;
    static com.qq.jce.WCS.AdminRequest cache_stAdminRequestInfo;

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.sMsg =  _is.readString(0, true);
        if(null == cache_mapUnit)
        {
            cache_mapUnit = new java.util.HashMap<String, java.util.ArrayList<String>>();
            String __var_15 = "";
            java.util.ArrayList<String> __var_16 = new java.util.ArrayList<String>();
            String __var_17 = "";
            ((java.util.ArrayList<String>)__var_16).add(__var_17);
            cache_mapUnit.put(__var_15, __var_16);
        }
        this.mapUnit = (java.util.Map<String, java.util.ArrayList<String>>) _is.read(cache_mapUnit, 1, true);
        if(null == cache_vecComponents)
        {
            cache_vecComponents = new java.util.ArrayList<com.qq.jce.WCS.ComponentUnitInfo>();
            com.qq.jce.WCS.ComponentUnitInfo __var_18 = new com.qq.jce.WCS.ComponentUnitInfo();
            ((java.util.ArrayList<com.qq.jce.WCS.ComponentUnitInfo>)cache_vecComponents).add(__var_18);
        }
        this.vecComponents = (java.util.ArrayList<com.qq.jce.WCS.ComponentUnitInfo>) _is.read(cache_vecComponents, 2, true);
        if(null == cache_stAdminRequestInfo)
        {
            cache_stAdminRequestInfo = new com.qq.jce.WCS.AdminRequest();
        }
        this.stAdminRequestInfo = (com.qq.jce.WCS.AdminRequest) _is.read(cache_stAdminRequestInfo, 3, true);
        this.lReleaseTime = (long) _is.read(lReleaseTime, 4, false);
        this.sRuleDesc =  _is.readString(5, false);
        this.lUpdateLimit = (long) _is.read(lUpdateLimit, 6, false);
        this.nEnablePeriod = (int) _is.read(nEnablePeriod, 7, false);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(sMsg, "sMsg");
        _ds.display(mapUnit, "mapUnit");
        _ds.display(vecComponents, "vecComponents");
        _ds.display(stAdminRequestInfo, "stAdminRequestInfo");
        _ds.display(lReleaseTime, "lReleaseTime");
        _ds.display(sRuleDesc, "sRuleDesc");
        _ds.display(lUpdateLimit, "lUpdateLimit");
        _ds.display(nEnablePeriod, "nEnablePeriod");
    }

    public void displaySimple(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.displaySimple(sMsg, true);
        _ds.displaySimple(mapUnit, true);
        _ds.displaySimple(vecComponents, true);
        _ds.displaySimple(stAdminRequestInfo, true);
        _ds.displaySimple(lReleaseTime, true);
        _ds.displaySimple(sRuleDesc, true);
        _ds.displaySimple(lUpdateLimit, true);
        _ds.displaySimple(nEnablePeriod, false);
    }

}

