// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/noahyang/connServiceInvalid.jce'
// **********************************************************************

package com.qq.jce.WCS;

public final class ModifyUpdateInfoRequest extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "WCS.ModifyUpdateInfoRequest";
    }

    public String fullClassName()
    {
        return "com.qq.jce.WCS.ModifyUpdateInfoRequest";
    }

    public java.util.Map<String, java.util.ArrayList<String>> mapUnit = null;

    public int eUpdateType = 0;

    public String sUpdateVersion = "";

    public String sUpdateNoteUrl = "";

    public String sUpdateModule = "";

    public String sDownloadUrl = "";

    public String sMd5 = "";

    public com.qq.jce.WCS.AdminRequest stAdminRequestInfo = null;

    public String sInstallParam = "";

    public long lReleaseTime = 0;

    public long lUpdateLimit = 0;

    public String sRuleDesc = "";

    public int nEnablePeriod = 0;

    public java.util.Map<String, java.util.ArrayList<String>> getMapUnit()
    {
        return mapUnit;
    }

    public void  setMapUnit(java.util.Map<String, java.util.ArrayList<String>> mapUnit)
    {
        this.mapUnit = mapUnit;
    }

    public int getEUpdateType()
    {
        return eUpdateType;
    }

    public void  setEUpdateType(int eUpdateType)
    {
        this.eUpdateType = eUpdateType;
    }

    public String getSUpdateVersion()
    {
        return sUpdateVersion;
    }

    public void  setSUpdateVersion(String sUpdateVersion)
    {
        this.sUpdateVersion = sUpdateVersion;
    }

    public String getSUpdateNoteUrl()
    {
        return sUpdateNoteUrl;
    }

    public void  setSUpdateNoteUrl(String sUpdateNoteUrl)
    {
        this.sUpdateNoteUrl = sUpdateNoteUrl;
    }

    public String getSUpdateModule()
    {
        return sUpdateModule;
    }

    public void  setSUpdateModule(String sUpdateModule)
    {
        this.sUpdateModule = sUpdateModule;
    }

    public String getSDownloadUrl()
    {
        return sDownloadUrl;
    }

    public void  setSDownloadUrl(String sDownloadUrl)
    {
        this.sDownloadUrl = sDownloadUrl;
    }

    public String getSMd5()
    {
        return sMd5;
    }

    public void  setSMd5(String sMd5)
    {
        this.sMd5 = sMd5;
    }

    public com.qq.jce.WCS.AdminRequest getStAdminRequestInfo()
    {
        return stAdminRequestInfo;
    }

    public void  setStAdminRequestInfo(com.qq.jce.WCS.AdminRequest stAdminRequestInfo)
    {
        this.stAdminRequestInfo = stAdminRequestInfo;
    }

    public String getSInstallParam()
    {
        return sInstallParam;
    }

    public void  setSInstallParam(String sInstallParam)
    {
        this.sInstallParam = sInstallParam;
    }

    public long getLReleaseTime()
    {
        return lReleaseTime;
    }

    public void  setLReleaseTime(long lReleaseTime)
    {
        this.lReleaseTime = lReleaseTime;
    }

    public long getLUpdateLimit()
    {
        return lUpdateLimit;
    }

    public void  setLUpdateLimit(long lUpdateLimit)
    {
        this.lUpdateLimit = lUpdateLimit;
    }

    public String getSRuleDesc()
    {
        return sRuleDesc;
    }

    public void  setSRuleDesc(String sRuleDesc)
    {
        this.sRuleDesc = sRuleDesc;
    }

    public int getNEnablePeriod()
    {
        return nEnablePeriod;
    }

    public void  setNEnablePeriod(int nEnablePeriod)
    {
        this.nEnablePeriod = nEnablePeriod;
    }

    public ModifyUpdateInfoRequest()
    {
    }

    public ModifyUpdateInfoRequest(java.util.Map<String, java.util.ArrayList<String>> mapUnit, int eUpdateType, String sUpdateVersion, String sUpdateNoteUrl, String sUpdateModule, String sDownloadUrl, String sMd5, com.qq.jce.WCS.AdminRequest stAdminRequestInfo, String sInstallParam, long lReleaseTime, long lUpdateLimit, String sRuleDesc, int nEnablePeriod)
    {
        this.mapUnit = mapUnit;
        this.eUpdateType = eUpdateType;
        this.sUpdateVersion = sUpdateVersion;
        this.sUpdateNoteUrl = sUpdateNoteUrl;
        this.sUpdateModule = sUpdateModule;
        this.sDownloadUrl = sDownloadUrl;
        this.sMd5 = sMd5;
        this.stAdminRequestInfo = stAdminRequestInfo;
        this.sInstallParam = sInstallParam;
        this.lReleaseTime = lReleaseTime;
        this.lUpdateLimit = lUpdateLimit;
        this.sRuleDesc = sRuleDesc;
        this.nEnablePeriod = nEnablePeriod;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        ModifyUpdateInfoRequest t = (ModifyUpdateInfoRequest) o;
        return (
            com.qq.taf.jce.JceUtil.equals(mapUnit, t.mapUnit) && 
            com.qq.taf.jce.JceUtil.equals(eUpdateType, t.eUpdateType) && 
            com.qq.taf.jce.JceUtil.equals(sUpdateVersion, t.sUpdateVersion) && 
            com.qq.taf.jce.JceUtil.equals(sUpdateNoteUrl, t.sUpdateNoteUrl) && 
            com.qq.taf.jce.JceUtil.equals(sUpdateModule, t.sUpdateModule) && 
            com.qq.taf.jce.JceUtil.equals(sDownloadUrl, t.sDownloadUrl) && 
            com.qq.taf.jce.JceUtil.equals(sMd5, t.sMd5) && 
            com.qq.taf.jce.JceUtil.equals(stAdminRequestInfo, t.stAdminRequestInfo) && 
            com.qq.taf.jce.JceUtil.equals(sInstallParam, t.sInstallParam) && 
            com.qq.taf.jce.JceUtil.equals(lReleaseTime, t.lReleaseTime) && 
            com.qq.taf.jce.JceUtil.equals(lUpdateLimit, t.lUpdateLimit) && 
            com.qq.taf.jce.JceUtil.equals(sRuleDesc, t.sRuleDesc) && 
            com.qq.taf.jce.JceUtil.equals(nEnablePeriod, t.nEnablePeriod) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(mapUnit, 0);
        _os.write(eUpdateType, 1);
        _os.write(sUpdateVersion, 2);
        _os.write(sUpdateNoteUrl, 3);
        if (null != sUpdateModule)
        {
            _os.write(sUpdateModule, 4);
        }
        _os.write(sDownloadUrl, 5);
        _os.write(sMd5, 6);
        _os.write(stAdminRequestInfo, 7);
        if (null != sInstallParam)
        {
            _os.write(sInstallParam, 8);
        }
        _os.write(lReleaseTime, 9);
        _os.write(lUpdateLimit, 10);
        if (null != sRuleDesc)
        {
            _os.write(sRuleDesc, 11);
        }
        _os.write(nEnablePeriod, 12);
    }

    static java.util.Map<String, java.util.ArrayList<String>> cache_mapUnit;
    static int cache_eUpdateType;
    static com.qq.jce.WCS.AdminRequest cache_stAdminRequestInfo;

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        if(null == cache_mapUnit)
        {
            cache_mapUnit = new java.util.HashMap<String, java.util.ArrayList<String>>();
            String __var_2 = "";
            java.util.ArrayList<String> __var_3 = new java.util.ArrayList<String>();
            String __var_4 = "";
            ((java.util.ArrayList<String>)__var_3).add(__var_4);
            cache_mapUnit.put(__var_2, __var_3);
        }
        this.mapUnit = (java.util.Map<String, java.util.ArrayList<String>>) _is.read(cache_mapUnit, 0, true);
        this.eUpdateType = (int) _is.read(eUpdateType, 1, true);
        this.sUpdateVersion =  _is.readString(2, true);
        this.sUpdateNoteUrl =  _is.readString(3, true);
        this.sUpdateModule =  _is.readString(4, false);
        this.sDownloadUrl =  _is.readString(5, true);
        this.sMd5 =  _is.readString(6, true);
        if(null == cache_stAdminRequestInfo)
        {
            cache_stAdminRequestInfo = new com.qq.jce.WCS.AdminRequest();
        }
        this.stAdminRequestInfo = (com.qq.jce.WCS.AdminRequest) _is.read(cache_stAdminRequestInfo, 7, true);
        this.sInstallParam =  _is.readString(8, false);
        this.lReleaseTime = (long) _is.read(lReleaseTime, 9, false);
        this.lUpdateLimit = (long) _is.read(lUpdateLimit, 10, false);
        this.sRuleDesc =  _is.readString(11, false);
        this.nEnablePeriod = (int) _is.read(nEnablePeriod, 12, false);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(mapUnit, "mapUnit");
        _ds.display(eUpdateType, "eUpdateType");
        _ds.display(sUpdateVersion, "sUpdateVersion");
        _ds.display(sUpdateNoteUrl, "sUpdateNoteUrl");
        _ds.display(sUpdateModule, "sUpdateModule");
        _ds.display(sDownloadUrl, "sDownloadUrl");
        _ds.display(sMd5, "sMd5");
        _ds.display(stAdminRequestInfo, "stAdminRequestInfo");
        _ds.display(sInstallParam, "sInstallParam");
        _ds.display(lReleaseTime, "lReleaseTime");
        _ds.display(lUpdateLimit, "lUpdateLimit");
        _ds.display(sRuleDesc, "sRuleDesc");
        _ds.display(nEnablePeriod, "nEnablePeriod");
    }

    public void displaySimple(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.displaySimple(mapUnit, true);
        _ds.displaySimple(eUpdateType, true);
        _ds.displaySimple(sUpdateVersion, true);
        _ds.displaySimple(sUpdateNoteUrl, true);
        _ds.displaySimple(sUpdateModule, true);
        _ds.displaySimple(sDownloadUrl, true);
        _ds.displaySimple(sMd5, true);
        _ds.displaySimple(stAdminRequestInfo, true);
        _ds.displaySimple(sInstallParam, true);
        _ds.displaySimple(lReleaseTime, true);
        _ds.displaySimple(lUpdateLimit, true);
        _ds.displaySimple(sRuleDesc, true);
        _ds.displaySimple(nEnablePeriod, false);
    }

}

