// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/noahyang/connServiceInvalid.jce'
// **********************************************************************

package com.qq.jce.WCS;

public final class ModifySDKVerifyInfoRequest extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "WCS.ModifySDKVerifyInfoRequest";
    }

    public String fullClassName()
    {
        return "com.qq.jce.WCS.ModifySDKVerifyInfoRequest";
    }

    public com.qq.jce.WCS.AdminRequest stAdminRequestInfo = null;

    public java.util.Map<String, java.util.ArrayList<String>> mapUnit = null;

    public int nExpire = 0;

    public long lReleaseTime = 0;

    public long lUpdateLimit = 0;

    public int nEnablePeriod = 0;

    public com.qq.jce.WCS.AdminRequest getStAdminRequestInfo()
    {
        return stAdminRequestInfo;
    }

    public void  setStAdminRequestInfo(com.qq.jce.WCS.AdminRequest stAdminRequestInfo)
    {
        this.stAdminRequestInfo = stAdminRequestInfo;
    }

    public java.util.Map<String, java.util.ArrayList<String>> getMapUnit()
    {
        return mapUnit;
    }

    public void  setMapUnit(java.util.Map<String, java.util.ArrayList<String>> mapUnit)
    {
        this.mapUnit = mapUnit;
    }

    public int getNExpire()
    {
        return nExpire;
    }

    public void  setNExpire(int nExpire)
    {
        this.nExpire = nExpire;
    }

    public long getLReleaseTime()
    {
        return lReleaseTime;
    }

    public void  setLReleaseTime(long lReleaseTime)
    {
        this.lReleaseTime = lReleaseTime;
    }

    public long getLUpdateLimit()
    {
        return lUpdateLimit;
    }

    public void  setLUpdateLimit(long lUpdateLimit)
    {
        this.lUpdateLimit = lUpdateLimit;
    }

    public int getNEnablePeriod()
    {
        return nEnablePeriod;
    }

    public void  setNEnablePeriod(int nEnablePeriod)
    {
        this.nEnablePeriod = nEnablePeriod;
    }

    public ModifySDKVerifyInfoRequest()
    {
    }

    public ModifySDKVerifyInfoRequest(com.qq.jce.WCS.AdminRequest stAdminRequestInfo, java.util.Map<String, java.util.ArrayList<String>> mapUnit, int nExpire, long lReleaseTime, long lUpdateLimit, int nEnablePeriod)
    {
        this.stAdminRequestInfo = stAdminRequestInfo;
        this.mapUnit = mapUnit;
        this.nExpire = nExpire;
        this.lReleaseTime = lReleaseTime;
        this.lUpdateLimit = lUpdateLimit;
        this.nEnablePeriod = nEnablePeriod;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        ModifySDKVerifyInfoRequest t = (ModifySDKVerifyInfoRequest) o;
        return (
            com.qq.taf.jce.JceUtil.equals(stAdminRequestInfo, t.stAdminRequestInfo) && 
            com.qq.taf.jce.JceUtil.equals(mapUnit, t.mapUnit) && 
            com.qq.taf.jce.JceUtil.equals(nExpire, t.nExpire) && 
            com.qq.taf.jce.JceUtil.equals(lReleaseTime, t.lReleaseTime) && 
            com.qq.taf.jce.JceUtil.equals(lUpdateLimit, t.lUpdateLimit) && 
            com.qq.taf.jce.JceUtil.equals(nEnablePeriod, t.nEnablePeriod) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(stAdminRequestInfo, 0);
        _os.write(mapUnit, 1);
        _os.write(nExpire, 2);
        _os.write(lReleaseTime, 3);
        _os.write(lUpdateLimit, 4);
        _os.write(nEnablePeriod, 5);
    }

    static com.qq.jce.WCS.AdminRequest cache_stAdminRequestInfo;
    static java.util.Map<String, java.util.ArrayList<String>> cache_mapUnit;

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        if(null == cache_stAdminRequestInfo)
        {
            cache_stAdminRequestInfo = new com.qq.jce.WCS.AdminRequest();
        }
        this.stAdminRequestInfo = (com.qq.jce.WCS.AdminRequest) _is.read(cache_stAdminRequestInfo, 0, true);
        if(null == cache_mapUnit)
        {
            cache_mapUnit = new java.util.HashMap<String, java.util.ArrayList<String>>();
            String __var_22 = "";
            java.util.ArrayList<String> __var_23 = new java.util.ArrayList<String>();
            String __var_24 = "";
            ((java.util.ArrayList<String>)__var_23).add(__var_24);
            cache_mapUnit.put(__var_22, __var_23);
        }
        this.mapUnit = (java.util.Map<String, java.util.ArrayList<String>>) _is.read(cache_mapUnit, 1, true);
        this.nExpire = (int) _is.read(nExpire, 2, true);
        this.lReleaseTime = (long) _is.read(lReleaseTime, 3, false);
        this.lUpdateLimit = (long) _is.read(lUpdateLimit, 4, false);
        this.nEnablePeriod = (int) _is.read(nEnablePeriod, 5, false);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(stAdminRequestInfo, "stAdminRequestInfo");
        _ds.display(mapUnit, "mapUnit");
        _ds.display(nExpire, "nExpire");
        _ds.display(lReleaseTime, "lReleaseTime");
        _ds.display(lUpdateLimit, "lUpdateLimit");
        _ds.display(nEnablePeriod, "nEnablePeriod");
    }

    public void displaySimple(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.displaySimple(stAdminRequestInfo, true);
        _ds.displaySimple(mapUnit, true);
        _ds.displaySimple(nExpire, true);
        _ds.displaySimple(lReleaseTime, true);
        _ds.displaySimple(lUpdateLimit, true);
        _ds.displaySimple(nEnablePeriod, false);
    }

}

