// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/joycefang/QQTipsjce-PC.jce'
// **********************************************************************

package com.qq.jce.WCS;

public final class QQTipsResponse extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "WCS.QQTipsResponse";
    }

    public String fullClassName()
    {
        return "com.qq.jce.WCS.QQTipsResponse";
    }

    public int eRet = 0;

    public java.util.ArrayList<com.qq.jce.WCS.QQTipsResult> vTipsResult = null;

    public int getERet()
    {
        return eRet;
    }

    public void  setERet(int eRet)
    {
        this.eRet = eRet;
    }

    public java.util.ArrayList<com.qq.jce.WCS.QQTipsResult> getVTipsResult()
    {
        return vTipsResult;
    }

    public void  setVTipsResult(java.util.ArrayList<com.qq.jce.WCS.QQTipsResult> vTipsResult)
    {
        this.vTipsResult = vTipsResult;
    }

    public QQTipsResponse()
    {
    }

    public QQTipsResponse(int eRet, java.util.ArrayList<com.qq.jce.WCS.QQTipsResult> vTipsResult)
    {
        this.eRet = eRet;
        this.vTipsResult = vTipsResult;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        QQTipsResponse t = (QQTipsResponse) o;
        return (
            com.qq.taf.jce.JceUtil.equals(eRet, t.eRet) && 
            com.qq.taf.jce.JceUtil.equals(vTipsResult, t.vTipsResult) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(eRet, 0);
        _os.write(vTipsResult, 1);
    }

    static int cache_eRet;
    static java.util.ArrayList<com.qq.jce.WCS.QQTipsResult> cache_vTipsResult;

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.eRet = (int) _is.read(eRet, 0, true);
        if(null == cache_vTipsResult)
        {
            cache_vTipsResult = new java.util.ArrayList<com.qq.jce.WCS.QQTipsResult>();
            com.qq.jce.WCS.QQTipsResult __var_3 = new com.qq.jce.WCS.QQTipsResult();
            ((java.util.ArrayList<com.qq.jce.WCS.QQTipsResult>)cache_vTipsResult).add(__var_3);
        }
        this.vTipsResult = (java.util.ArrayList<com.qq.jce.WCS.QQTipsResult>) _is.read(cache_vTipsResult, 1, true);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(eRet, "eRet");
        _ds.display(vTipsResult, "vTipsResult");
    }

    public void displaySimple(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.displaySimple(eRet, true);
        _ds.displaySimple(vTipsResult, false);
    }

}

