// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/joycefang/QQTipsjce-web.jce'
// **********************************************************************

package com.qq.jce.WCS;

public final class QQTipsFirstRelease extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "WCS.QQTipsFirstRelease";
    }

    public String fullClassName()
    {
        return "com.qq.jce.WCS.QQTipsFirstRelease";
    }

    public java.util.ArrayList<com.qq.jce.WCS.FirstReleaseAppInfo> vInfos = null;

    public java.util.ArrayList<com.qq.jce.WCS.FirstReleaseAppInfo> getVInfos()
    {
        return vInfos;
    }

    public void  setVInfos(java.util.ArrayList<com.qq.jce.WCS.FirstReleaseAppInfo> vInfos)
    {
        this.vInfos = vInfos;
    }

    public QQTipsFirstRelease()
    {
    }

    public QQTipsFirstRelease(java.util.ArrayList<com.qq.jce.WCS.FirstReleaseAppInfo> vInfos)
    {
        this.vInfos = vInfos;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        QQTipsFirstRelease t = (QQTipsFirstRelease) o;
        return (
            com.qq.taf.jce.JceUtil.equals(vInfos, t.vInfos) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(vInfos, 0);
    }

    static java.util.ArrayList<com.qq.jce.WCS.FirstReleaseAppInfo> cache_vInfos;

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        if(null == cache_vInfos)
        {
            cache_vInfos = new java.util.ArrayList<com.qq.jce.WCS.FirstReleaseAppInfo>();
            com.qq.jce.WCS.FirstReleaseAppInfo __var_1 = new com.qq.jce.WCS.FirstReleaseAppInfo();
            ((java.util.ArrayList<com.qq.jce.WCS.FirstReleaseAppInfo>)cache_vInfos).add(__var_1);
        }
        this.vInfos = (java.util.ArrayList<com.qq.jce.WCS.FirstReleaseAppInfo>) _is.read(cache_vInfos, 0, true);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(vInfos, "vInfos");
    }

    public void displaySimple(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.displaySimple(vInfos, false);
    }

}

