// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/joycefang/QQTipsjce-web.jce'
// **********************************************************************

package com.qq.jce.WCS;

public final class QQTipsJumpType implements java.io.Serializable
{
    private static QQTipsJumpType[] __values = new QQTipsJumpType[3];
    private int __value;
    private String __T = new String();

    public static final int _E_QQTIPS_JUMPTYPE_BATTERY_CHARGING = 800;
    public static final QQTipsJumpType E_QQTIPS_JUMPTYPE_BATTERY_CHARGING = new QQTipsJumpType(0,_E_QQTIPS_JUMPTYPE_BATTERY_CHARGING,"E_QQTIPS_JUMPTYPE_BATTERY_CHARGING");
    public static final int _E_QQTIPS_JUMPTYPE_PHOTO_MANAGE = 12;
    public static final QQTipsJumpType E_QQTIPS_JUMPTYPE_PHOTO_MANAGE = new QQTipsJumpType(1,_E_QQTIPS_JUMPTYPE_PHOTO_MANAGE,"E_QQTIPS_JUMPTYPE_PHOTO_MANAGE");
    public static final int _E_QQTIPS_JUMPTYPE_CLEAN = 72;
    public static final QQTipsJumpType E_QQTIPS_JUMPTYPE_CLEAN = new QQTipsJumpType(2,_E_QQTIPS_JUMPTYPE_CLEAN,"E_QQTIPS_JUMPTYPE_CLEAN");

    public static QQTipsJumpType convert(int val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].value() == val)
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public static QQTipsJumpType convert(String val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].toString().equals(val))
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public int value()
    {
        return __value;
    }

    public String toString()
    {
        return __T;
    }

    private QQTipsJumpType(int index, int val, String s)
    {
        __T = s;
        __value = val;
        __values[index] = this;
    }

}
