// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/joycefang/QQTipsjce-web.jce'
// **********************************************************************

package com.qq.jce.WCS;

public final class QQTipsResultHolder
{
    public QQTipsResultHolder()
    {
    }
    public QQTipsResultHolder(QQTipsResult value)
    {
        this.value = value;
    }

    public QQTipsResult value;
}
