// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/joycefang/QQTipsjce-web.jce'
// **********************************************************************

package com.qq.jce.WCS;

public final class QQTipsStrategy extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "WCS.QQTipsStrategy";
    }

    public String fullClassName()
    {
        return "com.qq.jce.WCS.QQTipsStrategy";
    }

    public short nCount = 0;

    public short nPeriod = 0;

    public short getNCount()
    {
        return nCount;
    }

    public void  setNCount(short nCount)
    {
        this.nCount = nCount;
    }

    public short getNPeriod()
    {
        return nPeriod;
    }

    public void  setNPeriod(short nPeriod)
    {
        this.nPeriod = nPeriod;
    }

    public QQTipsStrategy()
    {
    }

    public QQTipsStrategy(short nCount, short nPeriod)
    {
        this.nCount = nCount;
        this.nPeriod = nPeriod;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        QQTipsStrategy t = (QQTipsStrategy) o;
        return (
            com.qq.taf.jce.JceUtil.equals(nCount, t.nCount) && 
            com.qq.taf.jce.JceUtil.equals(nPeriod, t.nPeriod) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(nCount, 0);
        _os.write(nPeriod, 1);
    }


    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.nCount = (short) _is.read(nCount, 0, true);
        this.nPeriod = (short) _is.read(nPeriod, 1, true);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(nCount, "nCount");
        _ds.display(nPeriod, "nPeriod");
    }

    public void displaySimple(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.displaySimple(nCount, true);
        _ds.displaySimple(nPeriod, false);
    }

}

