// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/joycefang/QQTipsjce-web.jce'
// **********************************************************************

package com.qq.jce.WCS;

public final class QQTipsStatus implements java.io.Serializable
{
    private static QQTipsStatus[] __values = new QQTipsStatus[2];
    private int __value;
    private String __T = new String();

    public static final int _E_QQTIPS_STATUS_ENABLE = 0;
    public static final QQTipsStatus E_QQTIPS_STATUS_ENABLE = new QQTipsStatus(0,_E_QQTIPS_STATUS_ENABLE,"E_QQTIPS_STATUS_ENABLE");
    public static final int _E_QQTIPS_STATUS_DISABLE = 1;
    public static final QQTipsStatus E_QQTIPS_STATUS_DISABLE = new QQTipsStatus(1,_E_QQTIPS_STATUS_DISABLE,"E_QQTIPS_STATUS_DISABLE");

    public static QQTipsStatus convert(int val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].value() == val)
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public static QQTipsStatus convert(String val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].toString().equals(val))
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public int value()
    {
        return __value;
    }

    public String toString()
    {
        return __T;
    }

    private QQTipsStatus(int index, int val, String s)
    {
        __T = s;
        __value = val;
        __values[index] = this;
    }

}
