// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/noahyang/wirelessConn.jce'
// **********************************************************************

package com.qq.jce.WCS;

public final class QueryVirtualVersionRequestHolder
{
    public QueryVirtualVersionRequestHolder()
    {
    }
    public QueryVirtualVersionRequestHolder(QueryVirtualVersionRequest value)
    {
        this.value = value;
    }

    public QueryVirtualVersionRequest value;
}
