// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/noahyang/dock.jce'
// **********************************************************************

package com.qq.jce.WCS;

public final class QueryDockInfoRequestHolder
{
    public QueryDockInfoRequestHolder()
    {
    }
    public QueryDockInfoRequestHolder(QueryDockInfoRequest value)
    {
        this.value = value;
    }

    public QueryDockInfoRequest value;
}
