// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/noahyang/dock.jce'
// **********************************************************************

package com.qq.jce.WCS;

public final class QueryDockInfoResponse extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "WCS.QueryDockInfoResponse";
    }

    public String fullClassName()
    {
        return "com.qq.jce.WCS.QueryDockInfoResponse";
    }

    public int eResultCode = 0;

    public java.util.ArrayList<com.qq.jce.WCS.DockInfoElem> vecInfos = null;

    public long lReleaseTime = 0;

    public long lUpdateLimit = 0;

    public int nEnablePeriod = 0;

    public int eDockInfoStatus = 0;

    public String sDockDesc = "";

    public String sDockInvalidDesc = "";

    public boolean bRollbackFlag = false;

    public String sTargetVersion = "";

    public int getEResultCode()
    {
        return eResultCode;
    }

    public void  setEResultCode(int eResultCode)
    {
        this.eResultCode = eResultCode;
    }

    public java.util.ArrayList<com.qq.jce.WCS.DockInfoElem> getVecInfos()
    {
        return vecInfos;
    }

    public void  setVecInfos(java.util.ArrayList<com.qq.jce.WCS.DockInfoElem> vecInfos)
    {
        this.vecInfos = vecInfos;
    }

    public long getLReleaseTime()
    {
        return lReleaseTime;
    }

    public void  setLReleaseTime(long lReleaseTime)
    {
        this.lReleaseTime = lReleaseTime;
    }

    public long getLUpdateLimit()
    {
        return lUpdateLimit;
    }

    public void  setLUpdateLimit(long lUpdateLimit)
    {
        this.lUpdateLimit = lUpdateLimit;
    }

    public int getNEnablePeriod()
    {
        return nEnablePeriod;
    }

    public void  setNEnablePeriod(int nEnablePeriod)
    {
        this.nEnablePeriod = nEnablePeriod;
    }

    public int getEDockInfoStatus()
    {
        return eDockInfoStatus;
    }

    public void  setEDockInfoStatus(int eDockInfoStatus)
    {
        this.eDockInfoStatus = eDockInfoStatus;
    }

    public String getSDockDesc()
    {
        return sDockDesc;
    }

    public void  setSDockDesc(String sDockDesc)
    {
        this.sDockDesc = sDockDesc;
    }

    public String getSDockInvalidDesc()
    {
        return sDockInvalidDesc;
    }

    public void  setSDockInvalidDesc(String sDockInvalidDesc)
    {
        this.sDockInvalidDesc = sDockInvalidDesc;
    }

    public boolean getBRollbackFlag()
    {
        return bRollbackFlag;
    }

    public void  setBRollbackFlag(boolean bRollbackFlag)
    {
        this.bRollbackFlag = bRollbackFlag;
    }

    public String getSTargetVersion()
    {
        return sTargetVersion;
    }

    public void  setSTargetVersion(String sTargetVersion)
    {
        this.sTargetVersion = sTargetVersion;
    }

    public QueryDockInfoResponse()
    {
    }

    public QueryDockInfoResponse(int eResultCode, java.util.ArrayList<com.qq.jce.WCS.DockInfoElem> vecInfos, long lReleaseTime, long lUpdateLimit, int nEnablePeriod, int eDockInfoStatus, String sDockDesc, String sDockInvalidDesc, boolean bRollbackFlag, String sTargetVersion)
    {
        this.eResultCode = eResultCode;
        this.vecInfos = vecInfos;
        this.lReleaseTime = lReleaseTime;
        this.lUpdateLimit = lUpdateLimit;
        this.nEnablePeriod = nEnablePeriod;
        this.eDockInfoStatus = eDockInfoStatus;
        this.sDockDesc = sDockDesc;
        this.sDockInvalidDesc = sDockInvalidDesc;
        this.bRollbackFlag = bRollbackFlag;
        this.sTargetVersion = sTargetVersion;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        QueryDockInfoResponse t = (QueryDockInfoResponse) o;
        return (
            com.qq.taf.jce.JceUtil.equals(eResultCode, t.eResultCode) && 
            com.qq.taf.jce.JceUtil.equals(vecInfos, t.vecInfos) && 
            com.qq.taf.jce.JceUtil.equals(lReleaseTime, t.lReleaseTime) && 
            com.qq.taf.jce.JceUtil.equals(lUpdateLimit, t.lUpdateLimit) && 
            com.qq.taf.jce.JceUtil.equals(nEnablePeriod, t.nEnablePeriod) && 
            com.qq.taf.jce.JceUtil.equals(eDockInfoStatus, t.eDockInfoStatus) && 
            com.qq.taf.jce.JceUtil.equals(sDockDesc, t.sDockDesc) && 
            com.qq.taf.jce.JceUtil.equals(sDockInvalidDesc, t.sDockInvalidDesc) && 
            com.qq.taf.jce.JceUtil.equals(bRollbackFlag, t.bRollbackFlag) && 
            com.qq.taf.jce.JceUtil.equals(sTargetVersion, t.sTargetVersion) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(eResultCode, 0);
        _os.write(vecInfos, 1);
        _os.write(lReleaseTime, 2);
        _os.write(lUpdateLimit, 3);
        _os.write(nEnablePeriod, 4);
        _os.write(eDockInfoStatus, 5);
        if (null != sDockDesc)
        {
            _os.write(sDockDesc, 6);
        }
        if (null != sDockInvalidDesc)
        {
            _os.write(sDockInvalidDesc, 7);
        }
        _os.write(bRollbackFlag, 8);
        if (null != sTargetVersion)
        {
            _os.write(sTargetVersion, 9);
        }
    }

    static int cache_eResultCode;
    static java.util.ArrayList<com.qq.jce.WCS.DockInfoElem> cache_vecInfos;
    static int cache_eDockInfoStatus;

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.eResultCode = (int) _is.read(eResultCode, 0, true);
        if(null == cache_vecInfos)
        {
            cache_vecInfos = new java.util.ArrayList<com.qq.jce.WCS.DockInfoElem>();
            com.qq.jce.WCS.DockInfoElem __var_2 = new com.qq.jce.WCS.DockInfoElem();
            ((java.util.ArrayList<com.qq.jce.WCS.DockInfoElem>)cache_vecInfos).add(__var_2);
        }
        this.vecInfos = (java.util.ArrayList<com.qq.jce.WCS.DockInfoElem>) _is.read(cache_vecInfos, 1, true);
        this.lReleaseTime = (long) _is.read(lReleaseTime, 2, false);
        this.lUpdateLimit = (long) _is.read(lUpdateLimit, 3, false);
        this.nEnablePeriod = (int) _is.read(nEnablePeriod, 4, false);
        this.eDockInfoStatus = (int) _is.read(eDockInfoStatus, 5, false);
        this.sDockDesc =  _is.readString(6, false);
        this.sDockInvalidDesc =  _is.readString(7, false);
        this.bRollbackFlag = (boolean) _is.read(bRollbackFlag, 8, false);
        this.sTargetVersion =  _is.readString(9, false);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(eResultCode, "eResultCode");
        _ds.display(vecInfos, "vecInfos");
        _ds.display(lReleaseTime, "lReleaseTime");
        _ds.display(lUpdateLimit, "lUpdateLimit");
        _ds.display(nEnablePeriod, "nEnablePeriod");
        _ds.display(eDockInfoStatus, "eDockInfoStatus");
        _ds.display(sDockDesc, "sDockDesc");
        _ds.display(sDockInvalidDesc, "sDockInvalidDesc");
        _ds.display(bRollbackFlag, "bRollbackFlag");
        _ds.display(sTargetVersion, "sTargetVersion");
    }

    public void displaySimple(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.displaySimple(eResultCode, true);
        _ds.displaySimple(vecInfos, true);
        _ds.displaySimple(lReleaseTime, true);
        _ds.displaySimple(lUpdateLimit, true);
        _ds.displaySimple(nEnablePeriod, true);
        _ds.displaySimple(eDockInfoStatus, true);
        _ds.displaySimple(sDockDesc, true);
        _ds.displaySimple(sDockInvalidDesc, true);
        _ds.displaySimple(bRollbackFlag, true);
        _ds.displaySimple(sTargetVersion, false);
    }

}

