// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/noahyang/connServiceInvalid.jce'
// **********************************************************************

package com.qq.jce.WCS;

public final class QueryFixInfoResponse extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "WCS.QueryFixInfoResponse";
    }

    public String fullClassName()
    {
        return "com.qq.jce.WCS.QueryFixInfoResponse";
    }

    public int eResultCode = 0;

    public String sVersion = "";

    public String sDownloadURL = "";

    public String sMd5 = "";

    public String sModuleName = "";

    public long lReleaseTime = 0;

    public String sRuleDesc = "";

    public long lUpdateLimit = 0;

    public int nEnablePeriod = 0;

    public int getEResultCode()
    {
        return eResultCode;
    }

    public void  setEResultCode(int eResultCode)
    {
        this.eResultCode = eResultCode;
    }

    public String getSVersion()
    {
        return sVersion;
    }

    public void  setSVersion(String sVersion)
    {
        this.sVersion = sVersion;
    }

    public String getSDownloadURL()
    {
        return sDownloadURL;
    }

    public void  setSDownloadURL(String sDownloadURL)
    {
        this.sDownloadURL = sDownloadURL;
    }

    public String getSMd5()
    {
        return sMd5;
    }

    public void  setSMd5(String sMd5)
    {
        this.sMd5 = sMd5;
    }

    public String getSModuleName()
    {
        return sModuleName;
    }

    public void  setSModuleName(String sModuleName)
    {
        this.sModuleName = sModuleName;
    }

    public long getLReleaseTime()
    {
        return lReleaseTime;
    }

    public void  setLReleaseTime(long lReleaseTime)
    {
        this.lReleaseTime = lReleaseTime;
    }

    public String getSRuleDesc()
    {
        return sRuleDesc;
    }

    public void  setSRuleDesc(String sRuleDesc)
    {
        this.sRuleDesc = sRuleDesc;
    }

    public long getLUpdateLimit()
    {
        return lUpdateLimit;
    }

    public void  setLUpdateLimit(long lUpdateLimit)
    {
        this.lUpdateLimit = lUpdateLimit;
    }

    public int getNEnablePeriod()
    {
        return nEnablePeriod;
    }

    public void  setNEnablePeriod(int nEnablePeriod)
    {
        this.nEnablePeriod = nEnablePeriod;
    }

    public QueryFixInfoResponse()
    {
    }

    public QueryFixInfoResponse(int eResultCode, String sVersion, String sDownloadURL, String sMd5, String sModuleName, long lReleaseTime, String sRuleDesc, long lUpdateLimit, int nEnablePeriod)
    {
        this.eResultCode = eResultCode;
        this.sVersion = sVersion;
        this.sDownloadURL = sDownloadURL;
        this.sMd5 = sMd5;
        this.sModuleName = sModuleName;
        this.lReleaseTime = lReleaseTime;
        this.sRuleDesc = sRuleDesc;
        this.lUpdateLimit = lUpdateLimit;
        this.nEnablePeriod = nEnablePeriod;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        QueryFixInfoResponse t = (QueryFixInfoResponse) o;
        return (
            com.qq.taf.jce.JceUtil.equals(eResultCode, t.eResultCode) && 
            com.qq.taf.jce.JceUtil.equals(sVersion, t.sVersion) && 
            com.qq.taf.jce.JceUtil.equals(sDownloadURL, t.sDownloadURL) && 
            com.qq.taf.jce.JceUtil.equals(sMd5, t.sMd5) && 
            com.qq.taf.jce.JceUtil.equals(sModuleName, t.sModuleName) && 
            com.qq.taf.jce.JceUtil.equals(lReleaseTime, t.lReleaseTime) && 
            com.qq.taf.jce.JceUtil.equals(sRuleDesc, t.sRuleDesc) && 
            com.qq.taf.jce.JceUtil.equals(lUpdateLimit, t.lUpdateLimit) && 
            com.qq.taf.jce.JceUtil.equals(nEnablePeriod, t.nEnablePeriod) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(eResultCode, 0);
        _os.write(sVersion, 1);
        _os.write(sDownloadURL, 2);
        _os.write(sMd5, 3);
        if (null != sModuleName)
        {
            _os.write(sModuleName, 4);
        }
        _os.write(lReleaseTime, 5);
        if (null != sRuleDesc)
        {
            _os.write(sRuleDesc, 6);
        }
        _os.write(lUpdateLimit, 7);
        _os.write(nEnablePeriod, 8);
    }

    static int cache_eResultCode;

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.eResultCode = (int) _is.read(eResultCode, 0, true);
        this.sVersion =  _is.readString(1, true);
        this.sDownloadURL =  _is.readString(2, true);
        this.sMd5 =  _is.readString(3, true);
        this.sModuleName =  _is.readString(4, false);
        this.lReleaseTime = (long) _is.read(lReleaseTime, 5, false);
        this.sRuleDesc =  _is.readString(6, false);
        this.lUpdateLimit = (long) _is.read(lUpdateLimit, 7, false);
        this.nEnablePeriod = (int) _is.read(nEnablePeriod, 8, false);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(eResultCode, "eResultCode");
        _ds.display(sVersion, "sVersion");
        _ds.display(sDownloadURL, "sDownloadURL");
        _ds.display(sMd5, "sMd5");
        _ds.display(sModuleName, "sModuleName");
        _ds.display(lReleaseTime, "lReleaseTime");
        _ds.display(sRuleDesc, "sRuleDesc");
        _ds.display(lUpdateLimit, "lUpdateLimit");
        _ds.display(nEnablePeriod, "nEnablePeriod");
    }

    public void displaySimple(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.displaySimple(eResultCode, true);
        _ds.displaySimple(sVersion, true);
        _ds.displaySimple(sDownloadURL, true);
        _ds.displaySimple(sMd5, true);
        _ds.displaySimple(sModuleName, true);
        _ds.displaySimple(lReleaseTime, true);
        _ds.displaySimple(sRuleDesc, true);
        _ds.displaySimple(lUpdateLimit, true);
        _ds.displaySimple(nEnablePeriod, false);
    }

}

