// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/joycefang/QQTipsjce-web.jce'
// **********************************************************************

package com.qq.jce.WCS;

public final class SetQQTipsBatchRequest extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "WCS.SetQQTipsBatchRequest";
    }

    public String fullClassName()
    {
        return "com.qq.jce.WCS.SetQQTipsBatchRequest";
    }

    public java.util.ArrayList<com.qq.jce.WCS.SetQQTipsRequest> vReqs = null;

    public java.util.ArrayList<com.qq.jce.WCS.SetQQTipsRequest> getVReqs()
    {
        return vReqs;
    }

    public void  setVReqs(java.util.ArrayList<com.qq.jce.WCS.SetQQTipsRequest> vReqs)
    {
        this.vReqs = vReqs;
    }

    public SetQQTipsBatchRequest()
    {
    }

    public SetQQTipsBatchRequest(java.util.ArrayList<com.qq.jce.WCS.SetQQTipsRequest> vReqs)
    {
        this.vReqs = vReqs;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        SetQQTipsBatchRequest t = (SetQQTipsBatchRequest) o;
        return (
            com.qq.taf.jce.JceUtil.equals(vReqs, t.vReqs) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(vReqs, 0);
    }

    static java.util.ArrayList<com.qq.jce.WCS.SetQQTipsRequest> cache_vReqs;

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        if(null == cache_vReqs)
        {
            cache_vReqs = new java.util.ArrayList<com.qq.jce.WCS.SetQQTipsRequest>();
            com.qq.jce.WCS.SetQQTipsRequest __var_3 = new com.qq.jce.WCS.SetQQTipsRequest();
            ((java.util.ArrayList<com.qq.jce.WCS.SetQQTipsRequest>)cache_vReqs).add(__var_3);
        }
        this.vReqs = (java.util.ArrayList<com.qq.jce.WCS.SetQQTipsRequest>) _is.read(cache_vReqs, 0, true);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(vReqs, "vReqs");
    }

    public void displaySimple(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.displaySimple(vReqs, false);
    }

}

