// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/noahyang/you.jce'
// **********************************************************************

package com.qq.jce.WCS.cnst;

public interface COMMAND_ID_APP_UPDATE_UIN_RESP
{
    int value = 4046;
}
