// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/noahyang/wirelessConn.jce'
// **********************************************************************

package com.qq.jce.WCS.cnst;

public interface COMMAND_ID_ADMIN_QUERY_CONN_CHECK_VIRTUAL_VERSION_REQUEST
{
    int value = 3152;
}
