// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0.34 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/noahyang/dock.jce'
// **********************************************************************

package com.qq.jce.WCS.cnst;

public interface COMMAND_ID_QUERY_DOCK_INFO_REQUEST
{
    int value = 3031;
}
